-- Migration 018: seed media courses (Suno, Runway, Midjourney)
-- Generated by scripts/gen-media-courses.mjs — do not edit by hand.
-- These courses are path-only by default (show_in_daily=false): reached through
-- career paths (Music/Video/Image), not browsed in the Daily Learn grid.
-- Run AFTER migration 017 (adds show_in_daily). Safe to re-run.

-- ═══ suno-basic ═══
insert into courses (slug, title, description, tool, level, status, units, lessons, order_index, show_in_daily)
values ('suno-basic', 'Suno: ทำเพลงด้วย AI', 'สร้างเพลงเต็มเพลงพร้อมร้องจากข้อความ ตั้งแต่บอกสไตล์ เขียนเนื้อ ไปจนถึงคุมโครงสร้างเพลงแบบมือโปร', 'Suno', 'beginner', 'published', 3, 8, 99, false)
on conflict (slug) do update set title=excluded.title, description=excluded.description, tool=excluded.tool, level=excluded.level, status='published', units=excluded.units, lessons=excluded.lessons, show_in_daily=false;

insert into course_units (course_id, title, order_index)
select c.id, v.title, v.ord from courses c, (values
  ('รู้จัก Suno', 1),
  ('เขียน Prompt และเนื้อเพลง', 2),
  ('เทคนิคและใช้งานจริง', 3)
) as v(title, ord) where c.slug = 'suno-basic'
on conflict (course_id, order_index) do update set title = excluded.title;

insert into course_lessons (unit_id, title, kind, xp, order_index)
select u.id, v.title, v.kind, v.xp, v.ord
from course_units u join courses c on c.id = u.course_id, (values
  (1, 'Suno คืออะไร', 'lesson', 10, 1),
  (1, 'เริ่มเพลงแรกใน Simple Mode', 'lesson', 10, 2),
  (2, 'เขียนคำอธิบายสไตล์ให้แม่น', 'lesson', 10, 1),
  (2, 'เขียนเนื้อเพลง (Lyrics)', 'lesson', 10, 2),
  (2, 'Custom Mode: คุมทุกอย่าง', 'quiz', 15, 3),
  (3, 'โครงสร้างเพลงที่ฟังดูเป็นมืออาชีพ', 'lesson', 10, 1),
  (3, 'Extend และ Remix ต่อยอดเพลง', 'lesson', 10, 2),
  (3, 'เผยแพร่และลิขสิทธิ์ (เช็คพอยต์)', 'check', 30, 3)
) as v(uord, title, kind, xp, ord)
where c.slug = 'suno-basic' and u.order_index = v.uord
on conflict (unit_id, order_index) do update set title = excluded.title, kind = excluded.kind, xp = excluded.xp;

-- ═══ runway-basic ═══
insert into courses (slug, title, description, tool, level, status, units, lessons, order_index, show_in_daily)
values ('runway-basic', 'Runway: ทำวิดีโอด้วย AI', 'สร้างคลิปวิดีโอจากข้อความและภาพนิ่ง คุมมุมกล้องและการเคลื่อนไหว ทำคลิปสั้นใช้งานได้จริงตั้งแต่ศูนย์', 'Runway', 'beginner', 'published', 3, 8, 99, false)
on conflict (slug) do update set title=excluded.title, description=excluded.description, tool=excluded.tool, level=excluded.level, status='published', units=excluded.units, lessons=excluded.lessons, show_in_daily=false;

insert into course_units (course_id, title, order_index)
select c.id, v.title, v.ord from courses c, (values
  ('รู้จัก Runway', 1),
  ('คุมภาพและกล้อง', 2),
  ('ตัดต่อและงานจริง', 3)
) as v(title, ord) where c.slug = 'runway-basic'
on conflict (course_id, order_index) do update set title = excluded.title;

insert into course_lessons (unit_id, title, kind, xp, order_index)
select u.id, v.title, v.kind, v.xp, v.ord
from course_units u join courses c on c.id = u.course_id, (values
  (1, 'Runway คืออะไร', 'lesson', 10, 1),
  (1, 'Text-to-Video คลิปแรก', 'lesson', 10, 2),
  (2, 'คุมมุมกล้องและการเคลื่อนไหว', 'lesson', 10, 1),
  (2, 'Image-to-Video ทำภาพนิ่งให้ขยับ', 'lesson', 10, 2),
  (2, 'Motion Brush คุมการเคลื่อนเฉพาะจุด', 'quiz', 15, 3),
  (3, 'ต่อคลิปและคุมความต่อเนื่อง', 'lesson', 10, 1),
  (3, 'เสียงและการ Export', 'lesson', 10, 2),
  (3, 'ทำคลิปโฆษณาสั้น 1 ชิ้น (โปรเจกต์)', 'project', 40, 3)
) as v(uord, title, kind, xp, ord)
where c.slug = 'runway-basic' and u.order_index = v.uord
on conflict (unit_id, order_index) do update set title = excluded.title, kind = excluded.kind, xp = excluded.xp;

-- ═══ midjourney-basic ═══
insert into courses (slug, title, description, tool, level, status, units, lessons, order_index, show_in_daily)
values ('midjourney-basic', 'Midjourney: สร้างภาพด้วย AI', 'สร้างภาพคุณภาพสูงจากข้อความ เข้าใจโครงสร้าง prompt พารามิเตอร์ และคุมสไตล์ให้สม่ำเสมอเพื่อใช้งานจริง', 'Midjourney', 'beginner', 'published', 3, 8, 99, false)
on conflict (slug) do update set title=excluded.title, description=excluded.description, tool=excluded.tool, level=excluded.level, status='published', units=excluded.units, lessons=excluded.lessons, show_in_daily=false;

insert into course_units (course_id, title, order_index)
select c.id, v.title, v.ord from courses c, (values
  ('รู้จัก Midjourney', 1),
  ('เขียน Prompt และพารามิเตอร์', 2),
  ('ปรับแต่งและใช้งานจริง', 3)
) as v(title, ord) where c.slug = 'midjourney-basic'
on conflict (course_id, order_index) do update set title = excluded.title;

insert into course_lessons (unit_id, title, kind, xp, order_index)
select u.id, v.title, v.kind, v.xp, v.ord
from course_units u join courses c on c.id = u.course_id, (values
  (1, 'Midjourney คืออะไร', 'lesson', 10, 1),
  (1, 'คำสั่ง /imagine แรก', 'lesson', 10, 2),
  (2, 'โครงสร้าง Prompt ที่ดี', 'lesson', 10, 1),
  (2, 'พารามิเตอร์: --ar --v --style', 'lesson', 10, 2),
  (2, 'Image Prompt และภาพอ้างอิง', 'quiz', 15, 3),
  (3, 'Vary, Upscale และ Remix', 'lesson', 10, 1),
  (3, 'คุมสไตล์ให้สม่ำเสมอ (--sref --cref)', 'lesson', 10, 2),
  (3, 'นำภาพไปใช้จริงและลิขสิทธิ์ (เช็คพอยต์)', 'check', 30, 3)
) as v(uord, title, kind, xp, ord)
where c.slug = 'midjourney-basic' and u.order_index = v.uord
on conflict (unit_id, order_index) do update set title = excluded.title, kind = excluded.kind, xp = excluded.xp;

