-- Migration 020: seed daily courses (Lovable, Grok) + Pro courses (AI Skills, MCP, Advanced AI)
-- Generated by scripts/gen-daily-pro-courses.mjs — do not edit by hand.
-- Lovable/Grok: free daily courses. The three ai-*-pro courses are Pro-only
-- (is_pro=true) — Free users see them with a Pro badge and are sent to /upgrade.
-- Run AFTER migrations 017 (show_in_daily) + 019 (is_pro). Safe to re-run.

-- ═══ lovable-basic ═══
insert into courses (slug, title, description, tool, level, status, units, lessons, order_index, show_in_daily, is_pro)
values ('lovable-basic', 'Lovable: สร้างเว็บแอปด้วย AI', 'เปลี่ยนไอเดียเป็นเว็บแอปใช้งานได้จริงด้วยการแชต ตั้งแต่หน้าแรก เชื่อมฐานข้อมูล จนถึง deploy โดยไม่ต้องเขียนโค้ดเป็น', 'Lovable', 'beginner', 'published', 2, 6, 13, true, false)
on conflict (slug) do update set title=excluded.title, description=excluded.description, tool=excluded.tool, level=excluded.level, status='published', units=excluded.units, lessons=excluded.lessons, show_in_daily=true, is_pro=excluded.is_pro;

insert into course_units (course_id, title, order_index)
select c.id, v.title, v.ord from courses c, (values
  ('เริ่มต้นกับ Lovable', 1),
  ('ทำให้แอปใช้งานได้จริง', 2)
) as v(title, ord) where c.slug = 'lovable-basic'
on conflict (course_id, order_index) do update set title = excluded.title;

insert into course_lessons (unit_id, title, kind, xp, order_index)
select u.id, v.title, v.kind, v.xp, v.ord
from course_units u join courses c on c.id = u.course_id, (values
  (1, 'Lovable คืออะไร', 'lesson', 10, 1),
  (1, 'สร้างแอปแรกจาก prompt', 'lesson', 10, 2),
  (2, 'แก้ไขและปรับ UI ด้วยแชต', 'lesson', 10, 1),
  (2, 'เชื่อมฐานข้อมูลเก็บข้อมูลจริง', 'lesson', 10, 2),
  (2, 'ทำระบบล็อกอินเบื้องต้น', 'quiz', 15, 3),
  (2, 'เผยแพร่และข้อจำกัด (เช็คพอยต์)', 'check', 30, 4)
) as v(uord, title, kind, xp, ord)
where c.slug = 'lovable-basic' and u.order_index = v.uord
on conflict (unit_id, order_index) do update set title = excluded.title, kind = excluded.kind, xp = excluded.xp;

-- ═══ grok-basic ═══
insert into courses (slug, title, description, tool, level, status, units, lessons, order_index, show_in_daily, is_pro)
values ('grok-basic', 'Grok: ผู้ช่วย AI ที่ทันเหตุการณ์', 'ใช้ Grok จาก xAI ค้นข้อมูลเรียลไทม์ ถามข่าวปัจจุบัน สร้างภาพ และค้นคว้า พร้อมรู้ข้อควรระวังในการตรวจสอบข้อมูล', 'Grok', 'beginner', 'published', 2, 4, 14, true, false)
on conflict (slug) do update set title=excluded.title, description=excluded.description, tool=excluded.tool, level=excluded.level, status='published', units=excluded.units, lessons=excluded.lessons, show_in_daily=true, is_pro=excluded.is_pro;

insert into course_units (course_id, title, order_index)
select c.id, v.title, v.ord from courses c, (values
  ('รู้จัก Grok', 1),
  ('ใช้งานและข้อควรระวัง', 2)
) as v(title, ord) where c.slug = 'grok-basic'
on conflict (course_id, order_index) do update set title = excluded.title;

insert into course_lessons (unit_id, title, kind, xp, order_index)
select u.id, v.title, v.kind, v.xp, v.ord
from course_units u join courses c on c.id = u.course_id, (values
  (1, 'Grok คืออะไร', 'lesson', 10, 1),
  (1, 'ถามข่าวและเหตุการณ์ปัจจุบัน', 'lesson', 10, 2),
  (2, 'สร้างภาพและความสามารถอื่น', 'lesson', 10, 1),
  (2, 'ตรวจสอบข้อมูลและใช้อย่างรับผิดชอบ (เช็คพอยต์)', 'check', 30, 2)
) as v(uord, title, kind, xp, ord)
where c.slug = 'grok-basic' and u.order_index = v.uord
on conflict (unit_id, order_index) do update set title = excluded.title, kind = excluded.kind, xp = excluded.xp;

-- ═══ elevenlabs-basic ═══
insert into courses (slug, title, description, tool, level, status, units, lessons, order_index, show_in_daily, is_pro)
values ('elevenlabs-basic', 'ElevenLabs: เสียงพากย์ด้วย AI', 'เปลี่ยนข้อความเป็นเสียงพูดเหมือนคนจริง พากย์คลิป โคลนเสียง และทำเสียงประกอบ ใช้งานได้จริงตั้งแต่ศูนย์', 'ElevenLabs', 'beginner', 'published', 2, 5, 15, true, false)
on conflict (slug) do update set title=excluded.title, description=excluded.description, tool=excluded.tool, level=excluded.level, status='published', units=excluded.units, lessons=excluded.lessons, show_in_daily=true, is_pro=excluded.is_pro;

insert into course_units (course_id, title, order_index)
select c.id, v.title, v.ord from courses c, (values
  ('รู้จัก ElevenLabs', 1),
  ('ปรับแต่งและใช้งานจริง', 2)
) as v(title, ord) where c.slug = 'elevenlabs-basic'
on conflict (course_id, order_index) do update set title = excluded.title;

insert into course_lessons (unit_id, title, kind, xp, order_index)
select u.id, v.title, v.kind, v.xp, v.ord
from course_units u join courses c on c.id = u.course_id, (values
  (1, 'ElevenLabs คืออะไร', 'lesson', 10, 1),
  (1, 'แปลงข้อความเป็นเสียงครั้งแรก', 'lesson', 10, 2),
  (2, 'ปรับอารมณ์และความเป็นธรรมชาติ', 'lesson', 10, 1),
  (2, 'โคลนเสียงและจริยธรรม', 'lesson', 10, 2),
  (2, 'พากย์และแปลภาษาคลิป (เช็คพอยต์)', 'check', 30, 3)
) as v(uord, title, kind, xp, ord)
where c.slug = 'elevenlabs-basic' and u.order_index = v.uord
on conflict (unit_id, order_index) do update set title = excluded.title, kind = excluded.kind, xp = excluded.xp;

-- ═══ ai-skills-pro ═══
insert into courses (slug, title, description, tool, level, status, units, lessons, order_index, show_in_daily, is_pro)
values ('ai-skills-pro', 'AI Skills: สอน AI ให้ทำงานเฉพาะทาง', 'สร้างและใช้ Skill เพื่อสอน AI ให้ทำงานเฉพาะทางซ้ำๆ ได้อย่างสม่ำเสมอ ตั้งแต่โครงสร้างไฟล์ ไปจนถึงใช้กับงานจริง — สำหรับสมาชิก Pro', 'Claude', 'intermediate', 'published', 2, 4, 16, true, true)
on conflict (slug) do update set title=excluded.title, description=excluded.description, tool=excluded.tool, level=excluded.level, status='published', units=excluded.units, lessons=excluded.lessons, show_in_daily=true, is_pro=excluded.is_pro;

insert into course_units (course_id, title, order_index)
select c.id, v.title, v.ord from courses c, (values
  ('พื้นฐาน Skill', 1),
  ('สร้างและใช้งานจริง', 2)
) as v(title, ord) where c.slug = 'ai-skills-pro'
on conflict (course_id, order_index) do update set title = excluded.title;

insert into course_lessons (unit_id, title, kind, xp, order_index)
select u.id, v.title, v.kind, v.xp, v.ord
from course_units u join courses c on c.id = u.course_id, (values
  (1, 'Skill คืออะไร', 'lesson', 15, 1),
  (1, 'โครงสร้างของ Skill', 'lesson', 15, 2),
  (2, 'เขียน Skill แรกของคุณ', 'lesson', 15, 1),
  (2, 'จัดการหลาย Skill และทำงานเป็นทีม (เช็คพอยต์)', 'check', 35, 2)
) as v(uord, title, kind, xp, ord)
where c.slug = 'ai-skills-pro' and u.order_index = v.uord
on conflict (unit_id, order_index) do update set title = excluded.title, kind = excluded.kind, xp = excluded.xp;

-- ═══ ai-mcp-pro ═══
insert into courses (slug, title, description, tool, level, status, units, lessons, order_index, show_in_daily, is_pro)
values ('ai-mcp-pro', 'MCP: เชื่อม AI กับเครื่องมือและข้อมูลของคุณ', 'เข้าใจ Model Context Protocol — มาตรฐานที่ให้ AI เชื่อมต่อไฟล์ ฐานข้อมูล และบริการภายนอกได้อย่างปลอดภัย พร้อมใช้งานจริง — สำหรับสมาชิก Pro', 'Claude', 'advanced', 'published', 2, 4, 17, true, true)
on conflict (slug) do update set title=excluded.title, description=excluded.description, tool=excluded.tool, level=excluded.level, status='published', units=excluded.units, lessons=excluded.lessons, show_in_daily=true, is_pro=excluded.is_pro;

insert into course_units (course_id, title, order_index)
select c.id, v.title, v.ord from courses c, (values
  ('พื้นฐาน MCP', 1),
  ('ใช้งานและความปลอดภัย', 2)
) as v(title, ord) where c.slug = 'ai-mcp-pro'
on conflict (course_id, order_index) do update set title = excluded.title;

insert into course_lessons (unit_id, title, kind, xp, order_index)
select u.id, v.title, v.kind, v.xp, v.ord
from course_units u join courses c on c.id = u.course_id, (values
  (1, 'MCP คืออะไร', 'lesson', 15, 1),
  (1, 'MCP Server ทำงานอย่างไร', 'lesson', 15, 2),
  (2, 'เชื่อมและใช้ MCP กับงานจริง', 'lesson', 15, 1),
  (2, 'ความปลอดภัยและสิทธิ์ (เช็คพอยต์)', 'check', 35, 2)
) as v(uord, title, kind, xp, ord)
where c.slug = 'ai-mcp-pro' and u.order_index = v.uord
on conflict (unit_id, order_index) do update set title = excluded.title, kind = excluded.kind, xp = excluded.xp;

-- ═══ ai-advanced-pro ═══
insert into courses (slug, title, description, tool, level, status, units, lessons, order_index, show_in_daily, is_pro)
values ('ai-advanced-pro', 'AI ขั้นสูง: Agent, RAG และ Workflow', 'เทคนิคใช้ AI ระดับสูง: ทำงานหลายขั้น (chaining), agent ที่ใช้เครื่องมือเอง, RAG อ้างอิงข้อมูลของคุณ และออกแบบ workflow จริง — สำหรับสมาชิก Pro', 'Claude', 'advanced', 'published', 2, 4, 18, true, true)
on conflict (slug) do update set title=excluded.title, description=excluded.description, tool=excluded.tool, level=excluded.level, status='published', units=excluded.units, lessons=excluded.lessons, show_in_daily=true, is_pro=excluded.is_pro;

insert into course_units (course_id, title, order_index)
select c.id, v.title, v.ord from courses c, (values
  ('ทำงานหลายขั้นและ Agent', 1),
  ('ข้อมูลของคุณและ Workflow', 2)
) as v(title, ord) where c.slug = 'ai-advanced-pro'
on conflict (course_id, order_index) do update set title = excluded.title;

insert into course_lessons (unit_id, title, kind, xp, order_index)
select u.id, v.title, v.kind, v.xp, v.ord
from course_units u join courses c on c.id = u.course_id, (values
  (1, 'Prompt Chaining: แตกงานเป็นขั้น', 'lesson', 15, 1),
  (1, 'Agent: AI ที่ใช้เครื่องมือเองได้', 'lesson', 15, 2),
  (2, 'RAG: ให้ AI อ้างอิงข้อมูลของเรา', 'lesson', 15, 1),
  (2, 'ออกแบบ Workflow จริง (เช็คพอยต์)', 'check', 40, 2)
) as v(uord, title, kind, xp, ord)
where c.slug = 'ai-advanced-pro' and u.order_index = v.uord
on conflict (unit_id, order_index) do update set title = excluded.title, kind = excluded.kind, xp = excluded.xp;

