-- Migration 021: new career paths with steps mapped to real lesson content
-- Generated by scripts/gen-career-paths.mjs — do not edit by hand.
-- Adds: AI for Automation, Students, Writing, Productivity, Music, Video, Image.
-- Each step's title/xp/kind mirror the underlying course lesson it opens.
-- Run AFTER migrations 018 + 020 (the courses these paths reference). Safe to re-run.

-- ═══ ai-for-automation ═══
delete from path_steps where module_id in (select id from path_modules where path_id in (select id from career_paths where slug='ai-for-automation'));
delete from path_modules where path_id in (select id from career_paths where slug='ai-for-automation');
insert into career_paths (slug, title, tag, description, tone, tools, weeks, is_pro, is_published, order_index)
values ('ai-for-automation', 'AI for Automation', 'ใหม่', 'ใช้ AI ลดงานซ้ำและสร้างระบบอัตโนมัติ ตั้งแต่พรอมป์เป็นขั้น เขียนสคริปต์ ไปจนถึงเชื่อมเครื่องมือด้วย MCP', 'sky', ARRAY['ChatGPT','Gemini','Claude'], 4, true, true, 7)
on conflict (slug) do update set title=excluded.title, tag=excluded.tag, description=excluded.description, tone=excluded.tone, tools=excluded.tools, weeks=excluded.weeks, is_pro=excluded.is_pro, is_published=true, order_index=excluded.order_index;

insert into path_modules (path_id, title, order_index)
select cp.id, v.title, v.ord from career_paths cp, (values
  ('พื้นฐานสั่งงาน AI ให้แม่น', 1),
  ('พรอมป์ขั้นสูงและทำงานหลายขั้น', 2),
  ('เขียนสคริปต์อัตโนมัติด้วย AI', 3),
  ('จัดการเอกสารและทีมด้วย Claude', 4)
) as v(title, ord) where cp.slug = 'ai-for-automation';

insert into path_steps (module_id, title, kind, course_slug, lesson_num, xp, order_index)
select m.id, v.title, v.kind, v.course_slug, v.lesson_num, v.xp, v.ord
from path_modules m join career_paths cp on cp.id = m.path_id, (values
  (1, 'ChatGPT คืออะไร', 'lesson', 'chatgpt-basic', 1, 10, 1),
  (1, 'UI และการเริ่มต้นใช้งาน', 'lesson', 'chatgpt-basic', 2, 10, 2),
  (1, 'Models ต่างๆ (GPT-3.5 vs GPT-4o)', 'quiz', 'chatgpt-basic', 3, 15, 3),
  (1, 'Prompt คืออะไร', 'lesson', 'chatgpt-basic', 4, 10, 4),
  (1, 'ให้บทบาท (Role Prompting)', 'lesson', 'chatgpt-basic', 5, 10, 5),
  (1, 'บอกรูปแบบผลลัพธ์', 'quiz', 'chatgpt-basic', 6, 15, 6),
  (2, 'Chain of Thought Prompting', 'lesson', 'chatgpt-advanced', 1, 15, 1),
  (2, 'Few-shot Prompting', 'lesson', 'chatgpt-advanced', 2, 15, 2),
  (2, 'System Instructions', 'quiz', 'chatgpt-advanced', 3, 20, 3),
  (2, 'Code Interpreter คืออะไร', 'lesson', 'chatgpt-advanced', 4, 15, 4),
  (2, 'วิเคราะห์ข้อมูลด้วย Python', 'lesson', 'chatgpt-advanced', 5, 15, 5),
  (2, 'สร้างกราฟและ Visualization', 'checkpoint', 'chatgpt-advanced', 6, 20, 6),
  (2, 'DALL·E ใน ChatGPT', 'lesson', 'chatgpt-advanced', 7, 15, 7),
  (2, 'Web Search & Browsing', 'lesson', 'chatgpt-advanced', 8, 15, 8),
  (3, 'OpenAI Codex คืออะไร', 'lesson', 'codex-basic', 1, 10, 1),
  (3, 'Codex App vs ChatGPT', 'lesson', 'codex-basic', 2, 10, 2),
  (3, 'Tasks & Environments', 'quiz', 'codex-basic', 3, 15, 3),
  (3, 'สร้าง Task แรก', 'lesson', 'codex-basic', 4, 10, 4),
  (3, 'Branch & Sandbox', 'lesson', 'codex-basic', 5, 10, 5),
  (3, 'Review และ Approve', 'checkpoint', 'codex-basic', 6, 20, 6),
  (3, 'Debug ด้วย Codex', 'lesson', 'codex-basic', 7, 10, 7),
  (3, 'เขียน Test อัตโนมัติ', 'lesson', 'codex-basic', 8, 10, 8),
  (4, 'สรุปและย่อเอกสาร', 'lesson', 'claude-cowork', 1, 10, 1),
  (4, 'เขียนรายงานและ Memo', 'lesson', 'claude-cowork', 2, 10, 2),
  (4, 'แปลเอกสาร', 'quiz', 'claude-cowork', 3, 15, 3),
  (4, 'เขียน Email', 'lesson', 'claude-cowork', 4, 10, 4),
  (4, 'Meeting Notes & สรุปประชุม', 'lesson', 'claude-cowork', 5, 10, 5),
  (4, 'Presentation Outline', 'checkpoint', 'claude-cowork', 6, 20, 6),
  (4, 'Research ด้วย Claude', 'lesson', 'claude-cowork', 7, 10, 7),
  (4, 'วิเคราะห์ข้อมูลและตัวเลข', 'lesson', 'claude-cowork', 8, 10, 8)
) as v(mord, title, kind, course_slug, lesson_num, xp, ord)
where cp.slug = 'ai-for-automation' and m.order_index = v.mord;

-- ═══ ai-for-students ═══
delete from path_steps where module_id in (select id from path_modules where path_id in (select id from career_paths where slug='ai-for-students'));
delete from path_modules where path_id in (select id from career_paths where slug='ai-for-students');
insert into career_paths (slug, title, tag, description, tone, tools, weeks, is_pro, is_published, order_index)
values ('ai-for-students', 'AI for Students', 'ใหม่', 'ผู้ช่วยเรียนที่ใช้ได้จริง: สรุปเนื้อหา ติวสอบ ทำรายงาน และค้นคว้าอย่างมีวิจารณญาณ', 'mint', ARRAY['ChatGPT','Claude','Gemini'], 3, false, true, 8)
on conflict (slug) do update set title=excluded.title, tag=excluded.tag, description=excluded.description, tone=excluded.tone, tools=excluded.tools, weeks=excluded.weeks, is_pro=excluded.is_pro, is_published=true, order_index=excluded.order_index;

insert into path_modules (path_id, title, order_index)
select cp.id, v.title, v.ord from career_paths cp, (values
  ('เริ่มใช้ AI ช่วยเรียน', 1),
  ('สรุปและทำความเข้าใจเนื้อหา', 2),
  ('ค้นคว้าและอ้างอิงอย่างถูกต้อง', 3)
) as v(title, ord) where cp.slug = 'ai-for-students';

insert into path_steps (module_id, title, kind, course_slug, lesson_num, xp, order_index)
select m.id, v.title, v.kind, v.course_slug, v.lesson_num, v.xp, v.ord
from path_modules m join career_paths cp on cp.id = m.path_id, (values
  (1, 'ChatGPT คืออะไร', 'lesson', 'chatgpt-basic', 1, 10, 1),
  (1, 'UI และการเริ่มต้นใช้งาน', 'lesson', 'chatgpt-basic', 2, 10, 2),
  (1, 'Models ต่างๆ (GPT-3.5 vs GPT-4o)', 'quiz', 'chatgpt-basic', 3, 15, 3),
  (1, 'Prompt คืออะไร', 'lesson', 'chatgpt-basic', 4, 10, 4),
  (1, 'ให้บทบาท (Role Prompting)', 'lesson', 'chatgpt-basic', 5, 10, 5),
  (1, 'บอกรูปแบบผลลัพธ์', 'quiz', 'chatgpt-basic', 6, 15, 6),
  (2, 'Claude คืออะไร', 'lesson', 'claude-basic', 1, 10, 1),
  (2, 'Claude Models (Haiku, Sonnet, Opus)', 'lesson', 'claude-basic', 2, 10, 2),
  (2, 'เริ่มใช้ Claude.ai', 'quiz', 'claude-basic', 3, 15, 3),
  (2, 'สไตล์การตอบของ Claude', 'lesson', 'claude-basic', 4, 10, 4),
  (2, 'Long Context คืออะไร', 'lesson', 'claude-basic', 5, 10, 5),
  (2, 'Upload Files & Documents', 'checkpoint', 'claude-basic', 6, 20, 6),
  (2, 'Projects คืออะไร', 'lesson', 'claude-basic', 7, 10, 7),
  (2, 'Project Knowledge', 'lesson', 'claude-basic', 8, 10, 8),
  (3, 'Gemini คืออะไร', 'lesson', 'gemini-basic', 1, 10, 1),
  (3, 'Gemini Models (Flash, Pro, Ultra)', 'lesson', 'gemini-basic', 2, 10, 2),
  (3, 'เริ่มใช้ Gemini.google.com', 'quiz', 'gemini-basic', 3, 15, 3),
  (3, 'อัปโหลดรูปภาพ', 'lesson', 'gemini-basic', 4, 10, 4),
  (3, 'วิเคราะห์ไฟล์ PDF', 'lesson', 'gemini-basic', 5, 10, 5),
  (3, 'Voice & Video', 'checkpoint', 'gemini-basic', 6, 20, 6),
  (3, 'Gemini ใน Gmail', 'lesson', 'gemini-basic', 7, 10, 7),
  (3, 'Gemini ใน Google Docs', 'lesson', 'gemini-basic', 8, 10, 8)
) as v(mord, title, kind, course_slug, lesson_num, xp, ord)
where cp.slug = 'ai-for-students' and m.order_index = v.mord;

-- ═══ ai-for-writing ═══
delete from path_steps where module_id in (select id from path_modules where path_id in (select id from career_paths where slug='ai-for-writing'));
delete from path_modules where path_id in (select id from career_paths where slug='ai-for-writing');
insert into career_paths (slug, title, tag, description, tone, tools, weeks, is_pro, is_published, order_index)
values ('ai-for-writing', 'AI for Writing', 'ใหม่', 'เขียนงานทุกแบบให้เร็วและดีขึ้น: บทความ คอนเทนต์ อีเมล โดยคุมโทนและสไตล์ได้', 'violet', ARRAY['Claude','ChatGPT'], 3, false, true, 9)
on conflict (slug) do update set title=excluded.title, tag=excluded.tag, description=excluded.description, tone=excluded.tone, tools=excluded.tools, weeks=excluded.weeks, is_pro=excluded.is_pro, is_published=true, order_index=excluded.order_index;

insert into path_modules (path_id, title, order_index)
select cp.id, v.title, v.ord from career_paths cp, (values
  ('พื้นฐานการเขียนกับ AI', 1),
  ('งานเขียนยาวและเรียบเรียงกับ Claude', 2),
  ('ยกระดับงานเขียนขั้นสูง', 3)
) as v(title, ord) where cp.slug = 'ai-for-writing';

insert into path_steps (module_id, title, kind, course_slug, lesson_num, xp, order_index)
select m.id, v.title, v.kind, v.course_slug, v.lesson_num, v.xp, v.ord
from path_modules m join career_paths cp on cp.id = m.path_id, (values
  (1, 'ChatGPT คืออะไร', 'lesson', 'chatgpt-basic', 1, 10, 1),
  (1, 'UI และการเริ่มต้นใช้งาน', 'lesson', 'chatgpt-basic', 2, 10, 2),
  (1, 'Models ต่างๆ (GPT-3.5 vs GPT-4o)', 'quiz', 'chatgpt-basic', 3, 15, 3),
  (1, 'Prompt คืออะไร', 'lesson', 'chatgpt-basic', 4, 10, 4),
  (1, 'ให้บทบาท (Role Prompting)', 'lesson', 'chatgpt-basic', 5, 10, 5),
  (1, 'บอกรูปแบบผลลัพธ์', 'quiz', 'chatgpt-basic', 6, 15, 6),
  (2, 'Claude คืออะไร', 'lesson', 'claude-basic', 1, 10, 1),
  (2, 'Claude Models (Haiku, Sonnet, Opus)', 'lesson', 'claude-basic', 2, 10, 2),
  (2, 'เริ่มใช้ Claude.ai', 'quiz', 'claude-basic', 3, 15, 3),
  (2, 'สไตล์การตอบของ Claude', 'lesson', 'claude-basic', 4, 10, 4),
  (2, 'Long Context คืออะไร', 'lesson', 'claude-basic', 5, 10, 5),
  (2, 'Upload Files & Documents', 'checkpoint', 'claude-basic', 6, 20, 6),
  (2, 'Projects คืออะไร', 'lesson', 'claude-basic', 7, 10, 7),
  (2, 'Project Knowledge', 'lesson', 'claude-basic', 8, 10, 8),
  (3, 'Chain of Thought Prompting', 'lesson', 'chatgpt-advanced', 1, 15, 1),
  (3, 'Few-shot Prompting', 'lesson', 'chatgpt-advanced', 2, 15, 2),
  (3, 'System Instructions', 'quiz', 'chatgpt-advanced', 3, 20, 3),
  (3, 'Code Interpreter คืออะไร', 'lesson', 'chatgpt-advanced', 4, 15, 4),
  (3, 'วิเคราะห์ข้อมูลด้วย Python', 'lesson', 'chatgpt-advanced', 5, 15, 5),
  (3, 'สร้างกราฟและ Visualization', 'checkpoint', 'chatgpt-advanced', 6, 20, 6)
) as v(mord, title, kind, course_slug, lesson_num, xp, ord)
where cp.slug = 'ai-for-writing' and m.order_index = v.mord;

-- ═══ ai-for-productivity ═══
delete from path_steps where module_id in (select id from path_modules where path_id in (select id from career_paths where slug='ai-for-productivity'));
delete from path_modules where path_id in (select id from career_paths where slug='ai-for-productivity');
insert into career_paths (slug, title, tag, description, tone, tools, weeks, is_pro, is_published, order_index)
values ('ai-for-productivity', 'AI for Productivity', 'ใหม่', 'เพิ่มประสิทธิภาพงานประจำวัน: จัดการอีเมล สรุปประชุม วางแผนงาน และทำงานร่วมกับทีม', 'sun', ARRAY['ChatGPT','Claude','Gemini'], 3, false, true, 10)
on conflict (slug) do update set title=excluded.title, tag=excluded.tag, description=excluded.description, tone=excluded.tone, tools=excluded.tools, weeks=excluded.weeks, is_pro=excluded.is_pro, is_published=true, order_index=excluded.order_index;

insert into path_modules (path_id, title, order_index)
select cp.id, v.title, v.ord from career_paths cp, (values
  ('ใช้ AI กับงานประจำวัน', 1),
  ('ทำงานร่วมกับทีมด้วย Claude', 2),
  ('ค้นข้อมูลและตัดสินใจด้วย Gemini', 3)
) as v(title, ord) where cp.slug = 'ai-for-productivity';

insert into path_steps (module_id, title, kind, course_slug, lesson_num, xp, order_index)
select m.id, v.title, v.kind, v.course_slug, v.lesson_num, v.xp, v.ord
from path_modules m join career_paths cp on cp.id = m.path_id, (values
  (1, 'ChatGPT คืออะไร', 'lesson', 'chatgpt-basic', 1, 10, 1),
  (1, 'UI และการเริ่มต้นใช้งาน', 'lesson', 'chatgpt-basic', 2, 10, 2),
  (1, 'Models ต่างๆ (GPT-3.5 vs GPT-4o)', 'quiz', 'chatgpt-basic', 3, 15, 3),
  (1, 'Prompt คืออะไร', 'lesson', 'chatgpt-basic', 4, 10, 4),
  (1, 'ให้บทบาท (Role Prompting)', 'lesson', 'chatgpt-basic', 5, 10, 5),
  (1, 'บอกรูปแบบผลลัพธ์', 'quiz', 'chatgpt-basic', 6, 15, 6),
  (2, 'สรุปและย่อเอกสาร', 'lesson', 'claude-cowork', 1, 10, 1),
  (2, 'เขียนรายงานและ Memo', 'lesson', 'claude-cowork', 2, 10, 2),
  (2, 'แปลเอกสาร', 'quiz', 'claude-cowork', 3, 15, 3),
  (2, 'เขียน Email', 'lesson', 'claude-cowork', 4, 10, 4),
  (2, 'Meeting Notes & สรุปประชุม', 'lesson', 'claude-cowork', 5, 10, 5),
  (2, 'Presentation Outline', 'checkpoint', 'claude-cowork', 6, 20, 6),
  (2, 'Research ด้วย Claude', 'lesson', 'claude-cowork', 7, 10, 7),
  (2, 'วิเคราะห์ข้อมูลและตัวเลข', 'lesson', 'claude-cowork', 8, 10, 8),
  (3, 'Gemini คืออะไร', 'lesson', 'gemini-basic', 1, 10, 1),
  (3, 'Gemini Models (Flash, Pro, Ultra)', 'lesson', 'gemini-basic', 2, 10, 2),
  (3, 'เริ่มใช้ Gemini.google.com', 'quiz', 'gemini-basic', 3, 15, 3),
  (3, 'อัปโหลดรูปภาพ', 'lesson', 'gemini-basic', 4, 10, 4),
  (3, 'วิเคราะห์ไฟล์ PDF', 'lesson', 'gemini-basic', 5, 10, 5),
  (3, 'Voice & Video', 'checkpoint', 'gemini-basic', 6, 20, 6)
) as v(mord, title, kind, course_slug, lesson_num, xp, ord)
where cp.slug = 'ai-for-productivity' and m.order_index = v.mord;

-- ═══ ai-for-music ═══
delete from path_steps where module_id in (select id from path_modules where path_id in (select id from career_paths where slug='ai-for-music'));
delete from path_modules where path_id in (select id from career_paths where slug='ai-for-music');
insert into career_paths (slug, title, tag, description, tone, tools, weeks, is_pro, is_published, order_index)
values ('ai-for-music', 'AI for Music', 'ใหม่', 'ทำเพลงครบเพลงด้วย AI ตั้งแต่แต่งทำนอง เขียนเนื้อ ไปจนถึงโครงสร้างเพลงและเผยแพร่', 'pink', ARRAY['Suno','ChatGPT'], 2, true, true, 11)
on conflict (slug) do update set title=excluded.title, tag=excluded.tag, description=excluded.description, tone=excluded.tone, tools=excluded.tools, weeks=excluded.weeks, is_pro=excluded.is_pro, is_published=true, order_index=excluded.order_index;

insert into path_modules (path_id, title, order_index)
select cp.id, v.title, v.ord from career_paths cp, (values
  ('เขียนเนื้อเพลงด้วย AI', 1),
  ('สร้างเพลงด้วย Suno', 2)
) as v(title, ord) where cp.slug = 'ai-for-music';

insert into path_steps (module_id, title, kind, course_slug, lesson_num, xp, order_index)
select m.id, v.title, v.kind, v.course_slug, v.lesson_num, v.xp, v.ord
from path_modules m join career_paths cp on cp.id = m.path_id, (values
  (1, 'ChatGPT คืออะไร', 'lesson', 'chatgpt-basic', 1, 10, 1),
  (1, 'UI และการเริ่มต้นใช้งาน', 'lesson', 'chatgpt-basic', 2, 10, 2),
  (1, 'Models ต่างๆ (GPT-3.5 vs GPT-4o)', 'quiz', 'chatgpt-basic', 3, 15, 3),
  (1, 'Prompt คืออะไร', 'lesson', 'chatgpt-basic', 4, 10, 4),
  (2, 'Suno คืออะไร', 'lesson', 'suno-basic', 1, 10, 1),
  (2, 'เริ่มเพลงแรกใน Simple Mode', 'lesson', 'suno-basic', 2, 10, 2),
  (2, 'เขียนคำอธิบายสไตล์ให้แม่น', 'lesson', 'suno-basic', 3, 10, 3),
  (2, 'เขียนเนื้อเพลง (Lyrics)', 'lesson', 'suno-basic', 4, 10, 4),
  (2, 'Custom Mode: คุมทุกอย่าง', 'quiz', 'suno-basic', 5, 15, 5),
  (2, 'โครงสร้างเพลงที่ฟังดูเป็นมืออาชีพ', 'lesson', 'suno-basic', 6, 10, 6),
  (2, 'Extend และ Remix ต่อยอดเพลง', 'lesson', 'suno-basic', 7, 10, 7),
  (2, 'เผยแพร่และลิขสิทธิ์', 'checkpoint', 'suno-basic', 8, 30, 8)
) as v(mord, title, kind, course_slug, lesson_num, xp, ord)
where cp.slug = 'ai-for-music' and m.order_index = v.mord;

-- ═══ ai-for-video ═══
delete from path_steps where module_id in (select id from path_modules where path_id in (select id from career_paths where slug='ai-for-video'));
delete from path_modules where path_id in (select id from career_paths where slug='ai-for-video');
insert into career_paths (slug, title, tag, description, tone, tools, weeks, is_pro, is_published, order_index)
values ('ai-for-video', 'AI for Video', 'ใหม่', 'ทำคลิปวิดีโอด้วย AI: วางสคริปต์ สร้างภาพเคลื่อนไหว คุมกล้อง และตัดต่อเป็นคลิปใช้งานได้จริง', 'blue', ARRAY['Runway','ChatGPT','Suno'], 2, true, true, 12)
on conflict (slug) do update set title=excluded.title, tag=excluded.tag, description=excluded.description, tone=excluded.tone, tools=excluded.tools, weeks=excluded.weeks, is_pro=excluded.is_pro, is_published=true, order_index=excluded.order_index;

insert into path_modules (path_id, title, order_index)
select cp.id, v.title, v.ord from career_paths cp, (values
  ('วางสคริปต์และไอเดียด้วย AI', 1),
  ('สร้างวิดีโอด้วย Runway', 2)
) as v(title, ord) where cp.slug = 'ai-for-video';

insert into path_steps (module_id, title, kind, course_slug, lesson_num, xp, order_index)
select m.id, v.title, v.kind, v.course_slug, v.lesson_num, v.xp, v.ord
from path_modules m join career_paths cp on cp.id = m.path_id, (values
  (1, 'ChatGPT คืออะไร', 'lesson', 'chatgpt-basic', 1, 10, 1),
  (1, 'UI และการเริ่มต้นใช้งาน', 'lesson', 'chatgpt-basic', 2, 10, 2),
  (1, 'Models ต่างๆ (GPT-3.5 vs GPT-4o)', 'quiz', 'chatgpt-basic', 3, 15, 3),
  (1, 'Prompt คืออะไร', 'lesson', 'chatgpt-basic', 4, 10, 4),
  (2, 'Runway คืออะไร', 'lesson', 'runway-basic', 1, 10, 1),
  (2, 'Text-to-Video คลิปแรก', 'lesson', 'runway-basic', 2, 10, 2),
  (2, 'คุมมุมกล้องและการเคลื่อนไหว', 'lesson', 'runway-basic', 3, 10, 3),
  (2, 'Image-to-Video ทำภาพนิ่งให้ขยับ', 'lesson', 'runway-basic', 4, 10, 4),
  (2, 'Motion Brush คุมการเคลื่อนเฉพาะจุด', 'quiz', 'runway-basic', 5, 15, 5),
  (2, 'ต่อคลิปและคุมความต่อเนื่อง', 'lesson', 'runway-basic', 6, 10, 6),
  (2, 'เสียงและการ Export', 'lesson', 'runway-basic', 7, 10, 7),
  (2, 'ทำคลิปโฆษณาสั้น 1 ชิ้น', 'project', 'runway-basic', 8, 40, 8)
) as v(mord, title, kind, course_slug, lesson_num, xp, ord)
where cp.slug = 'ai-for-video' and m.order_index = v.mord;

-- ═══ ai-for-image ═══
delete from path_steps where module_id in (select id from path_modules where path_id in (select id from career_paths where slug='ai-for-image'));
delete from path_modules where path_id in (select id from career_paths where slug='ai-for-image');
insert into career_paths (slug, title, tag, description, tone, tools, weeks, is_pro, is_published, order_index)
values ('ai-for-image', 'AI for Image & Design', 'ใหม่', 'สร้างภาพคุณภาพสูงด้วย AI: เขียน prompt คุมสไตล์ พารามิเตอร์ และนำไปใช้งานแบรนด์จริง', 'violet', ARRAY['Midjourney','Claude'], 2, true, true, 13)
on conflict (slug) do update set title=excluded.title, tag=excluded.tag, description=excluded.description, tone=excluded.tone, tools=excluded.tools, weeks=excluded.weeks, is_pro=excluded.is_pro, is_published=true, order_index=excluded.order_index;

insert into path_modules (path_id, title, order_index)
select cp.id, v.title, v.ord from career_paths cp, (values
  ('พื้นฐานสร้างภาพด้วย Midjourney', 1),
  ('คุมสไตล์และใช้งานจริง', 2),
  ('งานออกแบบและภาพประกอบกับ Claude', 3)
) as v(title, ord) where cp.slug = 'ai-for-image';

insert into path_steps (module_id, title, kind, course_slug, lesson_num, xp, order_index)
select m.id, v.title, v.kind, v.course_slug, v.lesson_num, v.xp, v.ord
from path_modules m join career_paths cp on cp.id = m.path_id, (values
  (1, 'Midjourney คืออะไร', 'lesson', 'midjourney-basic', 1, 10, 1),
  (1, 'คำสั่ง /imagine แรก', 'lesson', 'midjourney-basic', 2, 10, 2),
  (1, 'โครงสร้าง Prompt ที่ดี', 'lesson', 'midjourney-basic', 3, 10, 3),
  (1, 'พารามิเตอร์: --ar --v --style', 'lesson', 'midjourney-basic', 4, 10, 4),
  (1, 'Image Prompt และภาพอ้างอิง', 'quiz', 'midjourney-basic', 5, 15, 5),
  (2, 'Vary, Upscale และ Remix', 'lesson', 'midjourney-basic', 6, 10, 1),
  (2, 'คุมสไตล์ให้สม่ำเสมอ (--sref --cref)', 'lesson', 'midjourney-basic', 7, 10, 2),
  (2, 'นำภาพไปใช้จริงและลิขสิทธิ์', 'checkpoint', 'midjourney-basic', 8, 30, 3),
  (3, 'AI ในกระบวนการออกแบบ', 'lesson', 'claude-design', 1, 10, 1),
  (3, 'Design Brief & Creative Brief', 'lesson', 'claude-design', 2, 10, 2),
  (3, 'Mood Board และ Reference', 'quiz', 'claude-design', 3, 15, 3),
  (3, 'UX Copy คืออะไร', 'lesson', 'claude-design', 4, 10, 4),
  (3, 'Error Messages และ Microcopy', 'lesson', 'claude-design', 5, 10, 5),
  (3, 'Onboarding Copy', 'checkpoint', 'claude-design', 6, 20, 6)
) as v(mord, title, kind, course_slug, lesson_num, xp, ord)
where cp.slug = 'ai-for-image' and m.order_index = v.mord;

