-- ════════════════════════════════════════════════════════════════════
-- APPLY ALL: new courses + career paths (migrations 017–021 combined)
-- Paste this whole file into Supabase SQL Editor and Run ONCE.
-- Statements run in order; each is idempotent (safe to re-run).
-- ════════════════════════════════════════════════════════════════════

-- ╔══ 017_course_visibility ══╗
-- Migration 017: per-course visibility in Daily Learn
-- Some courses (e.g. the media tracks: Suno music, Runway video, Midjourney
-- image) are meant to be reached THROUGH a career path, not browsed as a
-- standalone daily topic. This flag lets an admin choose: show in the
-- /daily-learn topic grid, or keep it path-only.
-- Run this in Supabase SQL Editor (safe to re-run).

alter table courses add column if not exists show_in_daily boolean not null default true;

comment on column courses.show_in_daily is
  'When false, the course is hidden from the Daily Learn topic grid but still usable inside career-path lessons.';


-- ╔══ 018_media_courses ══╗
-- Migration 018: seed media courses (Suno, Runway, Midjourney)
-- Generated by scripts/gen-media-courses.mjs — do not edit by hand.
-- These courses are path-only by default (show_in_daily=false): reached through
-- career paths (Music/Video/Image), not browsed in the Daily Learn grid.
-- Run AFTER migration 017 (adds show_in_daily). Safe to re-run.

-- ═══ suno-basic ═══
insert into courses (slug, title, description, tool, level, status, units, lessons, order_index, show_in_daily)
values ('suno-basic', 'Suno: ทำเพลงด้วย AI', 'สร้างเพลงเต็มเพลงพร้อมร้องจากข้อความ ตั้งแต่บอกสไตล์ เขียนเนื้อ ไปจนถึงคุมโครงสร้างเพลงแบบมือโปร', 'Suno', 'beginner', 'published', 3, 8, 99, false)
on conflict (slug) do update set title=excluded.title, description=excluded.description, tool=excluded.tool, level=excluded.level, status='published', units=excluded.units, lessons=excluded.lessons, show_in_daily=false;

insert into course_units (course_id, title, order_index)
select c.id, v.title, v.ord from courses c, (values
  ('รู้จัก Suno', 1),
  ('เขียน Prompt และเนื้อเพลง', 2),
  ('เทคนิคและใช้งานจริง', 3)
) as v(title, ord) where c.slug = 'suno-basic'
on conflict (course_id, order_index) do update set title = excluded.title;

insert into course_lessons (unit_id, title, kind, xp, order_index)
select u.id, v.title, v.kind, v.xp, v.ord
from course_units u join courses c on c.id = u.course_id, (values
  (1, 'Suno คืออะไร', 'lesson', 10, 1),
  (1, 'เริ่มเพลงแรกใน Simple Mode', 'lesson', 10, 2),
  (2, 'เขียนคำอธิบายสไตล์ให้แม่น', 'lesson', 10, 1),
  (2, 'เขียนเนื้อเพลง (Lyrics)', 'lesson', 10, 2),
  (2, 'Custom Mode: คุมทุกอย่าง', 'quiz', 15, 3),
  (3, 'โครงสร้างเพลงที่ฟังดูเป็นมืออาชีพ', 'lesson', 10, 1),
  (3, 'Extend และ Remix ต่อยอดเพลง', 'lesson', 10, 2),
  (3, 'เผยแพร่และลิขสิทธิ์ (เช็คพอยต์)', 'check', 30, 3)
) as v(uord, title, kind, xp, ord)
where c.slug = 'suno-basic' and u.order_index = v.uord
on conflict (unit_id, order_index) do update set title = excluded.title, kind = excluded.kind, xp = excluded.xp;

-- ═══ runway-basic ═══
insert into courses (slug, title, description, tool, level, status, units, lessons, order_index, show_in_daily)
values ('runway-basic', 'Runway: ทำวิดีโอด้วย AI', 'สร้างคลิปวิดีโอจากข้อความและภาพนิ่ง คุมมุมกล้องและการเคลื่อนไหว ทำคลิปสั้นใช้งานได้จริงตั้งแต่ศูนย์', 'Runway', 'beginner', 'published', 3, 8, 99, false)
on conflict (slug) do update set title=excluded.title, description=excluded.description, tool=excluded.tool, level=excluded.level, status='published', units=excluded.units, lessons=excluded.lessons, show_in_daily=false;

insert into course_units (course_id, title, order_index)
select c.id, v.title, v.ord from courses c, (values
  ('รู้จัก Runway', 1),
  ('คุมภาพและกล้อง', 2),
  ('ตัดต่อและงานจริง', 3)
) as v(title, ord) where c.slug = 'runway-basic'
on conflict (course_id, order_index) do update set title = excluded.title;

insert into course_lessons (unit_id, title, kind, xp, order_index)
select u.id, v.title, v.kind, v.xp, v.ord
from course_units u join courses c on c.id = u.course_id, (values
  (1, 'Runway คืออะไร', 'lesson', 10, 1),
  (1, 'Text-to-Video คลิปแรก', 'lesson', 10, 2),
  (2, 'คุมมุมกล้องและการเคลื่อนไหว', 'lesson', 10, 1),
  (2, 'Image-to-Video ทำภาพนิ่งให้ขยับ', 'lesson', 10, 2),
  (2, 'Motion Brush คุมการเคลื่อนเฉพาะจุด', 'quiz', 15, 3),
  (3, 'ต่อคลิปและคุมความต่อเนื่อง', 'lesson', 10, 1),
  (3, 'เสียงและการ Export', 'lesson', 10, 2),
  (3, 'ทำคลิปโฆษณาสั้น 1 ชิ้น (โปรเจกต์)', 'project', 40, 3)
) as v(uord, title, kind, xp, ord)
where c.slug = 'runway-basic' and u.order_index = v.uord
on conflict (unit_id, order_index) do update set title = excluded.title, kind = excluded.kind, xp = excluded.xp;

-- ═══ midjourney-basic ═══
insert into courses (slug, title, description, tool, level, status, units, lessons, order_index, show_in_daily)
values ('midjourney-basic', 'Midjourney: สร้างภาพด้วย AI', 'สร้างภาพคุณภาพสูงจากข้อความ เข้าใจโครงสร้าง prompt พารามิเตอร์ และคุมสไตล์ให้สม่ำเสมอเพื่อใช้งานจริง', 'Midjourney', 'beginner', 'published', 3, 8, 99, false)
on conflict (slug) do update set title=excluded.title, description=excluded.description, tool=excluded.tool, level=excluded.level, status='published', units=excluded.units, lessons=excluded.lessons, show_in_daily=false;

insert into course_units (course_id, title, order_index)
select c.id, v.title, v.ord from courses c, (values
  ('รู้จัก Midjourney', 1),
  ('เขียน Prompt และพารามิเตอร์', 2),
  ('ปรับแต่งและใช้งานจริง', 3)
) as v(title, ord) where c.slug = 'midjourney-basic'
on conflict (course_id, order_index) do update set title = excluded.title;

insert into course_lessons (unit_id, title, kind, xp, order_index)
select u.id, v.title, v.kind, v.xp, v.ord
from course_units u join courses c on c.id = u.course_id, (values
  (1, 'Midjourney คืออะไร', 'lesson', 10, 1),
  (1, 'คำสั่ง /imagine แรก', 'lesson', 10, 2),
  (2, 'โครงสร้าง Prompt ที่ดี', 'lesson', 10, 1),
  (2, 'พารามิเตอร์: --ar --v --style', 'lesson', 10, 2),
  (2, 'Image Prompt และภาพอ้างอิง', 'quiz', 15, 3),
  (3, 'Vary, Upscale และ Remix', 'lesson', 10, 1),
  (3, 'คุมสไตล์ให้สม่ำเสมอ (--sref --cref)', 'lesson', 10, 2),
  (3, 'นำภาพไปใช้จริงและลิขสิทธิ์ (เช็คพอยต์)', 'check', 30, 3)
) as v(uord, title, kind, xp, ord)
where c.slug = 'midjourney-basic' and u.order_index = v.uord
on conflict (unit_id, order_index) do update set title = excluded.title, kind = excluded.kind, xp = excluded.xp;



-- ╔══ 019_course_pro ══╗
-- Migration 019: Pro-only courses
-- Adds a per-course Pro lock (separate from career-path is_pro). Used for the
-- advanced daily tracks (AI Skills, MCP, Advanced AI) that should be available
-- to Pro members only. Free users see them in the grid with a Pro badge but
-- are sent to /upgrade when they try to open one.
-- Run this in Supabase SQL Editor (safe to re-run).

alter table courses add column if not exists is_pro boolean not null default false;

comment on column courses.is_pro is
  'When true, only Pro (or admin) users can open the course; Free users are sent to /upgrade.';


-- ╔══ 020_daily_pro_courses ══╗
-- Migration 020: seed daily courses (Lovable, Grok) + Pro courses (AI Skills, MCP, Advanced AI)
-- Generated by scripts/gen-daily-pro-courses.mjs — do not edit by hand.
-- Lovable/Grok: free daily courses. The three ai-*-pro courses are Pro-only
-- (is_pro=true) — Free users see them with a Pro badge and are sent to /upgrade.
-- Run AFTER migrations 017 (show_in_daily) + 019 (is_pro). Safe to re-run.

-- ═══ lovable-basic ═══
insert into courses (slug, title, description, tool, level, status, units, lessons, order_index, show_in_daily, is_pro)
values ('lovable-basic', 'Lovable: สร้างเว็บแอปด้วย AI', 'เปลี่ยนไอเดียเป็นเว็บแอปใช้งานได้จริงด้วยการแชต ตั้งแต่หน้าแรก เชื่อมฐานข้อมูล จนถึง deploy โดยไม่ต้องเขียนโค้ดเป็น', 'Lovable', 'beginner', 'published', 2, 6, 13, true, false)
on conflict (slug) do update set title=excluded.title, description=excluded.description, tool=excluded.tool, level=excluded.level, status='published', units=excluded.units, lessons=excluded.lessons, show_in_daily=true, is_pro=excluded.is_pro;

insert into course_units (course_id, title, order_index)
select c.id, v.title, v.ord from courses c, (values
  ('เริ่มต้นกับ Lovable', 1),
  ('ทำให้แอปใช้งานได้จริง', 2)
) as v(title, ord) where c.slug = 'lovable-basic'
on conflict (course_id, order_index) do update set title = excluded.title;

insert into course_lessons (unit_id, title, kind, xp, order_index)
select u.id, v.title, v.kind, v.xp, v.ord
from course_units u join courses c on c.id = u.course_id, (values
  (1, 'Lovable คืออะไร', 'lesson', 10, 1),
  (1, 'สร้างแอปแรกจาก prompt', 'lesson', 10, 2),
  (2, 'แก้ไขและปรับ UI ด้วยแชต', 'lesson', 10, 1),
  (2, 'เชื่อมฐานข้อมูลเก็บข้อมูลจริง', 'lesson', 10, 2),
  (2, 'ทำระบบล็อกอินเบื้องต้น', 'quiz', 15, 3),
  (2, 'เผยแพร่และข้อจำกัด (เช็คพอยต์)', 'check', 30, 4)
) as v(uord, title, kind, xp, ord)
where c.slug = 'lovable-basic' and u.order_index = v.uord
on conflict (unit_id, order_index) do update set title = excluded.title, kind = excluded.kind, xp = excluded.xp;

-- ═══ grok-basic ═══
insert into courses (slug, title, description, tool, level, status, units, lessons, order_index, show_in_daily, is_pro)
values ('grok-basic', 'Grok: ผู้ช่วย AI ที่ทันเหตุการณ์', 'ใช้ Grok จาก xAI ค้นข้อมูลเรียลไทม์ ถามข่าวปัจจุบัน สร้างภาพ และค้นคว้า พร้อมรู้ข้อควรระวังในการตรวจสอบข้อมูล', 'Grok', 'beginner', 'published', 2, 4, 14, true, false)
on conflict (slug) do update set title=excluded.title, description=excluded.description, tool=excluded.tool, level=excluded.level, status='published', units=excluded.units, lessons=excluded.lessons, show_in_daily=true, is_pro=excluded.is_pro;

insert into course_units (course_id, title, order_index)
select c.id, v.title, v.ord from courses c, (values
  ('รู้จัก Grok', 1),
  ('ใช้งานและข้อควรระวัง', 2)
) as v(title, ord) where c.slug = 'grok-basic'
on conflict (course_id, order_index) do update set title = excluded.title;

insert into course_lessons (unit_id, title, kind, xp, order_index)
select u.id, v.title, v.kind, v.xp, v.ord
from course_units u join courses c on c.id = u.course_id, (values
  (1, 'Grok คืออะไร', 'lesson', 10, 1),
  (1, 'ถามข่าวและเหตุการณ์ปัจจุบัน', 'lesson', 10, 2),
  (2, 'สร้างภาพและความสามารถอื่น', 'lesson', 10, 1),
  (2, 'ตรวจสอบข้อมูลและใช้อย่างรับผิดชอบ (เช็คพอยต์)', 'check', 30, 2)
) as v(uord, title, kind, xp, ord)
where c.slug = 'grok-basic' and u.order_index = v.uord
on conflict (unit_id, order_index) do update set title = excluded.title, kind = excluded.kind, xp = excluded.xp;

-- ═══ elevenlabs-basic ═══
insert into courses (slug, title, description, tool, level, status, units, lessons, order_index, show_in_daily, is_pro)
values ('elevenlabs-basic', 'ElevenLabs: เสียงพากย์ด้วย AI', 'เปลี่ยนข้อความเป็นเสียงพูดเหมือนคนจริง พากย์คลิป โคลนเสียง และทำเสียงประกอบ ใช้งานได้จริงตั้งแต่ศูนย์', 'ElevenLabs', 'beginner', 'published', 2, 5, 15, true, false)
on conflict (slug) do update set title=excluded.title, description=excluded.description, tool=excluded.tool, level=excluded.level, status='published', units=excluded.units, lessons=excluded.lessons, show_in_daily=true, is_pro=excluded.is_pro;

insert into course_units (course_id, title, order_index)
select c.id, v.title, v.ord from courses c, (values
  ('รู้จัก ElevenLabs', 1),
  ('ปรับแต่งและใช้งานจริง', 2)
) as v(title, ord) where c.slug = 'elevenlabs-basic'
on conflict (course_id, order_index) do update set title = excluded.title;

insert into course_lessons (unit_id, title, kind, xp, order_index)
select u.id, v.title, v.kind, v.xp, v.ord
from course_units u join courses c on c.id = u.course_id, (values
  (1, 'ElevenLabs คืออะไร', 'lesson', 10, 1),
  (1, 'แปลงข้อความเป็นเสียงครั้งแรก', 'lesson', 10, 2),
  (2, 'ปรับอารมณ์และความเป็นธรรมชาติ', 'lesson', 10, 1),
  (2, 'โคลนเสียงและจริยธรรม', 'lesson', 10, 2),
  (2, 'พากย์และแปลภาษาคลิป (เช็คพอยต์)', 'check', 30, 3)
) as v(uord, title, kind, xp, ord)
where c.slug = 'elevenlabs-basic' and u.order_index = v.uord
on conflict (unit_id, order_index) do update set title = excluded.title, kind = excluded.kind, xp = excluded.xp;

-- ═══ ai-skills-pro ═══
insert into courses (slug, title, description, tool, level, status, units, lessons, order_index, show_in_daily, is_pro)
values ('ai-skills-pro', 'AI Skills: สอน AI ให้ทำงานเฉพาะทาง', 'สร้างและใช้ Skill เพื่อสอน AI ให้ทำงานเฉพาะทางซ้ำๆ ได้อย่างสม่ำเสมอ ตั้งแต่โครงสร้างไฟล์ ไปจนถึงใช้กับงานจริง — สำหรับสมาชิก Pro', 'Claude', 'intermediate', 'published', 2, 4, 16, true, true)
on conflict (slug) do update set title=excluded.title, description=excluded.description, tool=excluded.tool, level=excluded.level, status='published', units=excluded.units, lessons=excluded.lessons, show_in_daily=true, is_pro=excluded.is_pro;

insert into course_units (course_id, title, order_index)
select c.id, v.title, v.ord from courses c, (values
  ('พื้นฐาน Skill', 1),
  ('สร้างและใช้งานจริง', 2)
) as v(title, ord) where c.slug = 'ai-skills-pro'
on conflict (course_id, order_index) do update set title = excluded.title;

insert into course_lessons (unit_id, title, kind, xp, order_index)
select u.id, v.title, v.kind, v.xp, v.ord
from course_units u join courses c on c.id = u.course_id, (values
  (1, 'Skill คืออะไร', 'lesson', 15, 1),
  (1, 'โครงสร้างของ Skill', 'lesson', 15, 2),
  (2, 'เขียน Skill แรกของคุณ', 'lesson', 15, 1),
  (2, 'จัดการหลาย Skill และทำงานเป็นทีม (เช็คพอยต์)', 'check', 35, 2)
) as v(uord, title, kind, xp, ord)
where c.slug = 'ai-skills-pro' and u.order_index = v.uord
on conflict (unit_id, order_index) do update set title = excluded.title, kind = excluded.kind, xp = excluded.xp;

-- ═══ ai-mcp-pro ═══
insert into courses (slug, title, description, tool, level, status, units, lessons, order_index, show_in_daily, is_pro)
values ('ai-mcp-pro', 'MCP: เชื่อม AI กับเครื่องมือและข้อมูลของคุณ', 'เข้าใจ Model Context Protocol — มาตรฐานที่ให้ AI เชื่อมต่อไฟล์ ฐานข้อมูล และบริการภายนอกได้อย่างปลอดภัย พร้อมใช้งานจริง — สำหรับสมาชิก Pro', 'Claude', 'advanced', 'published', 2, 4, 17, true, true)
on conflict (slug) do update set title=excluded.title, description=excluded.description, tool=excluded.tool, level=excluded.level, status='published', units=excluded.units, lessons=excluded.lessons, show_in_daily=true, is_pro=excluded.is_pro;

insert into course_units (course_id, title, order_index)
select c.id, v.title, v.ord from courses c, (values
  ('พื้นฐาน MCP', 1),
  ('ใช้งานและความปลอดภัย', 2)
) as v(title, ord) where c.slug = 'ai-mcp-pro'
on conflict (course_id, order_index) do update set title = excluded.title;

insert into course_lessons (unit_id, title, kind, xp, order_index)
select u.id, v.title, v.kind, v.xp, v.ord
from course_units u join courses c on c.id = u.course_id, (values
  (1, 'MCP คืออะไร', 'lesson', 15, 1),
  (1, 'MCP Server ทำงานอย่างไร', 'lesson', 15, 2),
  (2, 'เชื่อมและใช้ MCP กับงานจริง', 'lesson', 15, 1),
  (2, 'ความปลอดภัยและสิทธิ์ (เช็คพอยต์)', 'check', 35, 2)
) as v(uord, title, kind, xp, ord)
where c.slug = 'ai-mcp-pro' and u.order_index = v.uord
on conflict (unit_id, order_index) do update set title = excluded.title, kind = excluded.kind, xp = excluded.xp;

-- ═══ ai-advanced-pro ═══
insert into courses (slug, title, description, tool, level, status, units, lessons, order_index, show_in_daily, is_pro)
values ('ai-advanced-pro', 'AI ขั้นสูง: Agent, RAG และ Workflow', 'เทคนิคใช้ AI ระดับสูง: ทำงานหลายขั้น (chaining), agent ที่ใช้เครื่องมือเอง, RAG อ้างอิงข้อมูลของคุณ และออกแบบ workflow จริง — สำหรับสมาชิก Pro', 'Claude', 'advanced', 'published', 2, 4, 18, true, true)
on conflict (slug) do update set title=excluded.title, description=excluded.description, tool=excluded.tool, level=excluded.level, status='published', units=excluded.units, lessons=excluded.lessons, show_in_daily=true, is_pro=excluded.is_pro;

insert into course_units (course_id, title, order_index)
select c.id, v.title, v.ord from courses c, (values
  ('ทำงานหลายขั้นและ Agent', 1),
  ('ข้อมูลของคุณและ Workflow', 2)
) as v(title, ord) where c.slug = 'ai-advanced-pro'
on conflict (course_id, order_index) do update set title = excluded.title;

insert into course_lessons (unit_id, title, kind, xp, order_index)
select u.id, v.title, v.kind, v.xp, v.ord
from course_units u join courses c on c.id = u.course_id, (values
  (1, 'Prompt Chaining: แตกงานเป็นขั้น', 'lesson', 15, 1),
  (1, 'Agent: AI ที่ใช้เครื่องมือเองได้', 'lesson', 15, 2),
  (2, 'RAG: ให้ AI อ้างอิงข้อมูลของเรา', 'lesson', 15, 1),
  (2, 'ออกแบบ Workflow จริง (เช็คพอยต์)', 'check', 40, 2)
) as v(uord, title, kind, xp, ord)
where c.slug = 'ai-advanced-pro' and u.order_index = v.uord
on conflict (unit_id, order_index) do update set title = excluded.title, kind = excluded.kind, xp = excluded.xp;



-- ╔══ 021_new_career_paths ══╗
-- Migration 021: new career paths with steps mapped to real lesson content
-- Generated by scripts/gen-career-paths.mjs — do not edit by hand.
-- Adds: AI for Automation, Students, Writing, Productivity, Music, Video, Image.
-- Each step's title/xp/kind mirror the underlying course lesson it opens.
-- Run AFTER migrations 018 + 020 (the courses these paths reference). Safe to re-run.

-- ═══ ai-for-automation ═══
delete from path_steps where module_id in (select id from path_modules where path_id in (select id from career_paths where slug='ai-for-automation'));
delete from path_modules where path_id in (select id from career_paths where slug='ai-for-automation');
insert into career_paths (slug, title, tag, description, tone, tools, weeks, is_pro, is_published, order_index)
values ('ai-for-automation', 'AI for Automation', 'ใหม่', 'ใช้ AI ลดงานซ้ำและสร้างระบบอัตโนมัติ ตั้งแต่พรอมป์เป็นขั้น เขียนสคริปต์ ไปจนถึงเชื่อมเครื่องมือด้วย MCP', 'sky', ARRAY['ChatGPT','Gemini','Claude'], 4, true, true, 7)
on conflict (slug) do update set title=excluded.title, tag=excluded.tag, description=excluded.description, tone=excluded.tone, tools=excluded.tools, weeks=excluded.weeks, is_pro=excluded.is_pro, is_published=true, order_index=excluded.order_index;

insert into path_modules (path_id, title, order_index)
select cp.id, v.title, v.ord from career_paths cp, (values
  ('พื้นฐานสั่งงาน AI ให้แม่น', 1),
  ('พรอมป์ขั้นสูงและทำงานหลายขั้น', 2),
  ('เขียนสคริปต์อัตโนมัติด้วย AI', 3),
  ('จัดการเอกสารและทีมด้วย Claude', 4)
) as v(title, ord) where cp.slug = 'ai-for-automation';

insert into path_steps (module_id, title, kind, course_slug, lesson_num, xp, order_index)
select m.id, v.title, v.kind, v.course_slug, v.lesson_num, v.xp, v.ord
from path_modules m join career_paths cp on cp.id = m.path_id, (values
  (1, 'ChatGPT คืออะไร', 'lesson', 'chatgpt-basic', 1, 10, 1),
  (1, 'UI และการเริ่มต้นใช้งาน', 'lesson', 'chatgpt-basic', 2, 10, 2),
  (1, 'Models ต่างๆ (GPT-3.5 vs GPT-4o)', 'quiz', 'chatgpt-basic', 3, 15, 3),
  (1, 'Prompt คืออะไร', 'lesson', 'chatgpt-basic', 4, 10, 4),
  (1, 'ให้บทบาท (Role Prompting)', 'lesson', 'chatgpt-basic', 5, 10, 5),
  (1, 'บอกรูปแบบผลลัพธ์', 'quiz', 'chatgpt-basic', 6, 15, 6),
  (2, 'Chain of Thought Prompting', 'lesson', 'chatgpt-advanced', 1, 15, 1),
  (2, 'Few-shot Prompting', 'lesson', 'chatgpt-advanced', 2, 15, 2),
  (2, 'System Instructions', 'quiz', 'chatgpt-advanced', 3, 20, 3),
  (2, 'Code Interpreter คืออะไร', 'lesson', 'chatgpt-advanced', 4, 15, 4),
  (2, 'วิเคราะห์ข้อมูลด้วย Python', 'lesson', 'chatgpt-advanced', 5, 15, 5),
  (2, 'สร้างกราฟและ Visualization', 'checkpoint', 'chatgpt-advanced', 6, 20, 6),
  (2, 'DALL·E ใน ChatGPT', 'lesson', 'chatgpt-advanced', 7, 15, 7),
  (2, 'Web Search & Browsing', 'lesson', 'chatgpt-advanced', 8, 15, 8),
  (3, 'OpenAI Codex คืออะไร', 'lesson', 'codex-basic', 1, 10, 1),
  (3, 'Codex App vs ChatGPT', 'lesson', 'codex-basic', 2, 10, 2),
  (3, 'Tasks & Environments', 'quiz', 'codex-basic', 3, 15, 3),
  (3, 'สร้าง Task แรก', 'lesson', 'codex-basic', 4, 10, 4),
  (3, 'Branch & Sandbox', 'lesson', 'codex-basic', 5, 10, 5),
  (3, 'Review และ Approve', 'checkpoint', 'codex-basic', 6, 20, 6),
  (3, 'Debug ด้วย Codex', 'lesson', 'codex-basic', 7, 10, 7),
  (3, 'เขียน Test อัตโนมัติ', 'lesson', 'codex-basic', 8, 10, 8),
  (4, 'สรุปและย่อเอกสาร', 'lesson', 'claude-cowork', 1, 10, 1),
  (4, 'เขียนรายงานและ Memo', 'lesson', 'claude-cowork', 2, 10, 2),
  (4, 'แปลเอกสาร', 'quiz', 'claude-cowork', 3, 15, 3),
  (4, 'เขียน Email', 'lesson', 'claude-cowork', 4, 10, 4),
  (4, 'Meeting Notes & สรุปประชุม', 'lesson', 'claude-cowork', 5, 10, 5),
  (4, 'Presentation Outline', 'checkpoint', 'claude-cowork', 6, 20, 6),
  (4, 'Research ด้วย Claude', 'lesson', 'claude-cowork', 7, 10, 7),
  (4, 'วิเคราะห์ข้อมูลและตัวเลข', 'lesson', 'claude-cowork', 8, 10, 8)
) as v(mord, title, kind, course_slug, lesson_num, xp, ord)
where cp.slug = 'ai-for-automation' and m.order_index = v.mord;

-- ═══ ai-for-students ═══
delete from path_steps where module_id in (select id from path_modules where path_id in (select id from career_paths where slug='ai-for-students'));
delete from path_modules where path_id in (select id from career_paths where slug='ai-for-students');
insert into career_paths (slug, title, tag, description, tone, tools, weeks, is_pro, is_published, order_index)
values ('ai-for-students', 'AI for Students', 'ใหม่', 'ผู้ช่วยเรียนที่ใช้ได้จริง: สรุปเนื้อหา ติวสอบ ทำรายงาน และค้นคว้าอย่างมีวิจารณญาณ', 'mint', ARRAY['ChatGPT','Claude','Gemini'], 3, true, true, 8)
on conflict (slug) do update set title=excluded.title, tag=excluded.tag, description=excluded.description, tone=excluded.tone, tools=excluded.tools, weeks=excluded.weeks, is_pro=excluded.is_pro, is_published=true, order_index=excluded.order_index;

insert into path_modules (path_id, title, order_index)
select cp.id, v.title, v.ord from career_paths cp, (values
  ('เริ่มใช้ AI ช่วยเรียน', 1),
  ('สรุปและทำความเข้าใจเนื้อหา', 2),
  ('ค้นคว้าและอ้างอิงอย่างถูกต้อง', 3)
) as v(title, ord) where cp.slug = 'ai-for-students';

insert into path_steps (module_id, title, kind, course_slug, lesson_num, xp, order_index)
select m.id, v.title, v.kind, v.course_slug, v.lesson_num, v.xp, v.ord
from path_modules m join career_paths cp on cp.id = m.path_id, (values
  (1, 'ChatGPT คืออะไร', 'lesson', 'chatgpt-basic', 1, 10, 1),
  (1, 'UI และการเริ่มต้นใช้งาน', 'lesson', 'chatgpt-basic', 2, 10, 2),
  (1, 'Models ต่างๆ (GPT-3.5 vs GPT-4o)', 'quiz', 'chatgpt-basic', 3, 15, 3),
  (1, 'Prompt คืออะไร', 'lesson', 'chatgpt-basic', 4, 10, 4),
  (1, 'ให้บทบาท (Role Prompting)', 'lesson', 'chatgpt-basic', 5, 10, 5),
  (1, 'บอกรูปแบบผลลัพธ์', 'quiz', 'chatgpt-basic', 6, 15, 6),
  (2, 'Claude คืออะไร', 'lesson', 'claude-basic', 1, 10, 1),
  (2, 'Claude Models (Haiku, Sonnet, Opus)', 'lesson', 'claude-basic', 2, 10, 2),
  (2, 'เริ่มใช้ Claude.ai', 'quiz', 'claude-basic', 3, 15, 3),
  (2, 'สไตล์การตอบของ Claude', 'lesson', 'claude-basic', 4, 10, 4),
  (2, 'Long Context คืออะไร', 'lesson', 'claude-basic', 5, 10, 5),
  (2, 'Upload Files & Documents', 'checkpoint', 'claude-basic', 6, 20, 6),
  (2, 'Projects คืออะไร', 'lesson', 'claude-basic', 7, 10, 7),
  (2, 'Project Knowledge', 'lesson', 'claude-basic', 8, 10, 8),
  (3, 'Gemini คืออะไร', 'lesson', 'gemini-basic', 1, 10, 1),
  (3, 'Gemini Models (Flash, Pro, Ultra)', 'lesson', 'gemini-basic', 2, 10, 2),
  (3, 'เริ่มใช้ Gemini.google.com', 'quiz', 'gemini-basic', 3, 15, 3),
  (3, 'อัปโหลดรูปภาพ', 'lesson', 'gemini-basic', 4, 10, 4),
  (3, 'วิเคราะห์ไฟล์ PDF', 'lesson', 'gemini-basic', 5, 10, 5),
  (3, 'Voice & Video', 'checkpoint', 'gemini-basic', 6, 20, 6),
  (3, 'Gemini ใน Gmail', 'lesson', 'gemini-basic', 7, 10, 7),
  (3, 'Gemini ใน Google Docs', 'lesson', 'gemini-basic', 8, 10, 8)
) as v(mord, title, kind, course_slug, lesson_num, xp, ord)
where cp.slug = 'ai-for-students' and m.order_index = v.mord;

-- ═══ ai-for-writing ═══
delete from path_steps where module_id in (select id from path_modules where path_id in (select id from career_paths where slug='ai-for-writing'));
delete from path_modules where path_id in (select id from career_paths where slug='ai-for-writing');
insert into career_paths (slug, title, tag, description, tone, tools, weeks, is_pro, is_published, order_index)
values ('ai-for-writing', 'AI for Writing', 'ใหม่', 'เขียนงานทุกแบบให้เร็วและดีขึ้น: บทความ คอนเทนต์ อีเมล โดยคุมโทนและสไตล์ได้', 'violet', ARRAY['Claude','ChatGPT'], 3, true, true, 9)
on conflict (slug) do update set title=excluded.title, tag=excluded.tag, description=excluded.description, tone=excluded.tone, tools=excluded.tools, weeks=excluded.weeks, is_pro=excluded.is_pro, is_published=true, order_index=excluded.order_index;

insert into path_modules (path_id, title, order_index)
select cp.id, v.title, v.ord from career_paths cp, (values
  ('พื้นฐานการเขียนกับ AI', 1),
  ('งานเขียนยาวและเรียบเรียงกับ Claude', 2),
  ('ยกระดับงานเขียนขั้นสูง', 3)
) as v(title, ord) where cp.slug = 'ai-for-writing';

insert into path_steps (module_id, title, kind, course_slug, lesson_num, xp, order_index)
select m.id, v.title, v.kind, v.course_slug, v.lesson_num, v.xp, v.ord
from path_modules m join career_paths cp on cp.id = m.path_id, (values
  (1, 'ChatGPT คืออะไร', 'lesson', 'chatgpt-basic', 1, 10, 1),
  (1, 'UI และการเริ่มต้นใช้งาน', 'lesson', 'chatgpt-basic', 2, 10, 2),
  (1, 'Models ต่างๆ (GPT-3.5 vs GPT-4o)', 'quiz', 'chatgpt-basic', 3, 15, 3),
  (1, 'Prompt คืออะไร', 'lesson', 'chatgpt-basic', 4, 10, 4),
  (1, 'ให้บทบาท (Role Prompting)', 'lesson', 'chatgpt-basic', 5, 10, 5),
  (1, 'บอกรูปแบบผลลัพธ์', 'quiz', 'chatgpt-basic', 6, 15, 6),
  (2, 'Claude คืออะไร', 'lesson', 'claude-basic', 1, 10, 1),
  (2, 'Claude Models (Haiku, Sonnet, Opus)', 'lesson', 'claude-basic', 2, 10, 2),
  (2, 'เริ่มใช้ Claude.ai', 'quiz', 'claude-basic', 3, 15, 3),
  (2, 'สไตล์การตอบของ Claude', 'lesson', 'claude-basic', 4, 10, 4),
  (2, 'Long Context คืออะไร', 'lesson', 'claude-basic', 5, 10, 5),
  (2, 'Upload Files & Documents', 'checkpoint', 'claude-basic', 6, 20, 6),
  (2, 'Projects คืออะไร', 'lesson', 'claude-basic', 7, 10, 7),
  (2, 'Project Knowledge', 'lesson', 'claude-basic', 8, 10, 8),
  (3, 'Chain of Thought Prompting', 'lesson', 'chatgpt-advanced', 1, 15, 1),
  (3, 'Few-shot Prompting', 'lesson', 'chatgpt-advanced', 2, 15, 2),
  (3, 'System Instructions', 'quiz', 'chatgpt-advanced', 3, 20, 3),
  (3, 'Code Interpreter คืออะไร', 'lesson', 'chatgpt-advanced', 4, 15, 4),
  (3, 'วิเคราะห์ข้อมูลด้วย Python', 'lesson', 'chatgpt-advanced', 5, 15, 5),
  (3, 'สร้างกราฟและ Visualization', 'checkpoint', 'chatgpt-advanced', 6, 20, 6)
) as v(mord, title, kind, course_slug, lesson_num, xp, ord)
where cp.slug = 'ai-for-writing' and m.order_index = v.mord;

-- ═══ ai-for-productivity ═══
delete from path_steps where module_id in (select id from path_modules where path_id in (select id from career_paths where slug='ai-for-productivity'));
delete from path_modules where path_id in (select id from career_paths where slug='ai-for-productivity');
insert into career_paths (slug, title, tag, description, tone, tools, weeks, is_pro, is_published, order_index)
values ('ai-for-productivity', 'AI for Productivity', 'ใหม่', 'เพิ่มประสิทธิภาพงานประจำวัน: จัดการอีเมล สรุปประชุม วางแผนงาน และทำงานร่วมกับทีม', 'sun', ARRAY['ChatGPT','Claude','Gemini'], 3, true, true, 10)
on conflict (slug) do update set title=excluded.title, tag=excluded.tag, description=excluded.description, tone=excluded.tone, tools=excluded.tools, weeks=excluded.weeks, is_pro=excluded.is_pro, is_published=true, order_index=excluded.order_index;

insert into path_modules (path_id, title, order_index)
select cp.id, v.title, v.ord from career_paths cp, (values
  ('ใช้ AI กับงานประจำวัน', 1),
  ('ทำงานร่วมกับทีมด้วย Claude', 2),
  ('ค้นข้อมูลและตัดสินใจด้วย Gemini', 3)
) as v(title, ord) where cp.slug = 'ai-for-productivity';

insert into path_steps (module_id, title, kind, course_slug, lesson_num, xp, order_index)
select m.id, v.title, v.kind, v.course_slug, v.lesson_num, v.xp, v.ord
from path_modules m join career_paths cp on cp.id = m.path_id, (values
  (1, 'ChatGPT คืออะไร', 'lesson', 'chatgpt-basic', 1, 10, 1),
  (1, 'UI และการเริ่มต้นใช้งาน', 'lesson', 'chatgpt-basic', 2, 10, 2),
  (1, 'Models ต่างๆ (GPT-3.5 vs GPT-4o)', 'quiz', 'chatgpt-basic', 3, 15, 3),
  (1, 'Prompt คืออะไร', 'lesson', 'chatgpt-basic', 4, 10, 4),
  (1, 'ให้บทบาท (Role Prompting)', 'lesson', 'chatgpt-basic', 5, 10, 5),
  (1, 'บอกรูปแบบผลลัพธ์', 'quiz', 'chatgpt-basic', 6, 15, 6),
  (2, 'สรุปและย่อเอกสาร', 'lesson', 'claude-cowork', 1, 10, 1),
  (2, 'เขียนรายงานและ Memo', 'lesson', 'claude-cowork', 2, 10, 2),
  (2, 'แปลเอกสาร', 'quiz', 'claude-cowork', 3, 15, 3),
  (2, 'เขียน Email', 'lesson', 'claude-cowork', 4, 10, 4),
  (2, 'Meeting Notes & สรุปประชุม', 'lesson', 'claude-cowork', 5, 10, 5),
  (2, 'Presentation Outline', 'checkpoint', 'claude-cowork', 6, 20, 6),
  (2, 'Research ด้วย Claude', 'lesson', 'claude-cowork', 7, 10, 7),
  (2, 'วิเคราะห์ข้อมูลและตัวเลข', 'lesson', 'claude-cowork', 8, 10, 8),
  (3, 'Gemini คืออะไร', 'lesson', 'gemini-basic', 1, 10, 1),
  (3, 'Gemini Models (Flash, Pro, Ultra)', 'lesson', 'gemini-basic', 2, 10, 2),
  (3, 'เริ่มใช้ Gemini.google.com', 'quiz', 'gemini-basic', 3, 15, 3),
  (3, 'อัปโหลดรูปภาพ', 'lesson', 'gemini-basic', 4, 10, 4),
  (3, 'วิเคราะห์ไฟล์ PDF', 'lesson', 'gemini-basic', 5, 10, 5),
  (3, 'Voice & Video', 'checkpoint', 'gemini-basic', 6, 20, 6)
) as v(mord, title, kind, course_slug, lesson_num, xp, ord)
where cp.slug = 'ai-for-productivity' and m.order_index = v.mord;

-- ═══ ai-for-music ═══
delete from path_steps where module_id in (select id from path_modules where path_id in (select id from career_paths where slug='ai-for-music'));
delete from path_modules where path_id in (select id from career_paths where slug='ai-for-music');
insert into career_paths (slug, title, tag, description, tone, tools, weeks, is_pro, is_published, order_index)
values ('ai-for-music', 'AI for Music', 'ใหม่', 'ทำเพลงครบเพลงด้วย AI ตั้งแต่แต่งทำนอง เขียนเนื้อ ไปจนถึงโครงสร้างเพลงและเผยแพร่', 'pink', ARRAY['Suno','ChatGPT'], 2, true, true, 11)
on conflict (slug) do update set title=excluded.title, tag=excluded.tag, description=excluded.description, tone=excluded.tone, tools=excluded.tools, weeks=excluded.weeks, is_pro=excluded.is_pro, is_published=true, order_index=excluded.order_index;

insert into path_modules (path_id, title, order_index)
select cp.id, v.title, v.ord from career_paths cp, (values
  ('เขียนเนื้อเพลงด้วย AI', 1),
  ('สร้างเพลงด้วย Suno', 2)
) as v(title, ord) where cp.slug = 'ai-for-music';

insert into path_steps (module_id, title, kind, course_slug, lesson_num, xp, order_index)
select m.id, v.title, v.kind, v.course_slug, v.lesson_num, v.xp, v.ord
from path_modules m join career_paths cp on cp.id = m.path_id, (values
  (1, 'ChatGPT คืออะไร', 'lesson', 'chatgpt-basic', 1, 10, 1),
  (1, 'UI และการเริ่มต้นใช้งาน', 'lesson', 'chatgpt-basic', 2, 10, 2),
  (1, 'Models ต่างๆ (GPT-3.5 vs GPT-4o)', 'quiz', 'chatgpt-basic', 3, 15, 3),
  (1, 'Prompt คืออะไร', 'lesson', 'chatgpt-basic', 4, 10, 4),
  (2, 'Suno คืออะไร', 'lesson', 'suno-basic', 1, 10, 1),
  (2, 'เริ่มเพลงแรกใน Simple Mode', 'lesson', 'suno-basic', 2, 10, 2),
  (2, 'เขียนคำอธิบายสไตล์ให้แม่น', 'lesson', 'suno-basic', 3, 10, 3),
  (2, 'เขียนเนื้อเพลง (Lyrics)', 'lesson', 'suno-basic', 4, 10, 4),
  (2, 'Custom Mode: คุมทุกอย่าง', 'quiz', 'suno-basic', 5, 15, 5),
  (2, 'โครงสร้างเพลงที่ฟังดูเป็นมืออาชีพ', 'lesson', 'suno-basic', 6, 10, 6),
  (2, 'Extend และ Remix ต่อยอดเพลง', 'lesson', 'suno-basic', 7, 10, 7),
  (2, 'เผยแพร่และลิขสิทธิ์', 'checkpoint', 'suno-basic', 8, 30, 8)
) as v(mord, title, kind, course_slug, lesson_num, xp, ord)
where cp.slug = 'ai-for-music' and m.order_index = v.mord;

-- ═══ ai-for-video ═══
delete from path_steps where module_id in (select id from path_modules where path_id in (select id from career_paths where slug='ai-for-video'));
delete from path_modules where path_id in (select id from career_paths where slug='ai-for-video');
insert into career_paths (slug, title, tag, description, tone, tools, weeks, is_pro, is_published, order_index)
values ('ai-for-video', 'AI for Video', 'ใหม่', 'ทำคลิปวิดีโอด้วย AI: วางสคริปต์ สร้างภาพเคลื่อนไหว คุมกล้อง และตัดต่อเป็นคลิปใช้งานได้จริง', 'blue', ARRAY['Runway','ChatGPT','Suno'], 2, true, true, 12)
on conflict (slug) do update set title=excluded.title, tag=excluded.tag, description=excluded.description, tone=excluded.tone, tools=excluded.tools, weeks=excluded.weeks, is_pro=excluded.is_pro, is_published=true, order_index=excluded.order_index;

insert into path_modules (path_id, title, order_index)
select cp.id, v.title, v.ord from career_paths cp, (values
  ('วางสคริปต์และไอเดียด้วย AI', 1),
  ('สร้างวิดีโอด้วย Runway', 2)
) as v(title, ord) where cp.slug = 'ai-for-video';

insert into path_steps (module_id, title, kind, course_slug, lesson_num, xp, order_index)
select m.id, v.title, v.kind, v.course_slug, v.lesson_num, v.xp, v.ord
from path_modules m join career_paths cp on cp.id = m.path_id, (values
  (1, 'ChatGPT คืออะไร', 'lesson', 'chatgpt-basic', 1, 10, 1),
  (1, 'UI และการเริ่มต้นใช้งาน', 'lesson', 'chatgpt-basic', 2, 10, 2),
  (1, 'Models ต่างๆ (GPT-3.5 vs GPT-4o)', 'quiz', 'chatgpt-basic', 3, 15, 3),
  (1, 'Prompt คืออะไร', 'lesson', 'chatgpt-basic', 4, 10, 4),
  (2, 'Runway คืออะไร', 'lesson', 'runway-basic', 1, 10, 1),
  (2, 'Text-to-Video คลิปแรก', 'lesson', 'runway-basic', 2, 10, 2),
  (2, 'คุมมุมกล้องและการเคลื่อนไหว', 'lesson', 'runway-basic', 3, 10, 3),
  (2, 'Image-to-Video ทำภาพนิ่งให้ขยับ', 'lesson', 'runway-basic', 4, 10, 4),
  (2, 'Motion Brush คุมการเคลื่อนเฉพาะจุด', 'quiz', 'runway-basic', 5, 15, 5),
  (2, 'ต่อคลิปและคุมความต่อเนื่อง', 'lesson', 'runway-basic', 6, 10, 6),
  (2, 'เสียงและการ Export', 'lesson', 'runway-basic', 7, 10, 7),
  (2, 'ทำคลิปโฆษณาสั้น 1 ชิ้น', 'project', 'runway-basic', 8, 40, 8)
) as v(mord, title, kind, course_slug, lesson_num, xp, ord)
where cp.slug = 'ai-for-video' and m.order_index = v.mord;

-- ═══ ai-for-image ═══
delete from path_steps where module_id in (select id from path_modules where path_id in (select id from career_paths where slug='ai-for-image'));
delete from path_modules where path_id in (select id from career_paths where slug='ai-for-image');
insert into career_paths (slug, title, tag, description, tone, tools, weeks, is_pro, is_published, order_index)
values ('ai-for-image', 'AI for Image & Design', 'ใหม่', 'สร้างภาพคุณภาพสูงด้วย AI: เขียน prompt คุมสไตล์ พารามิเตอร์ และนำไปใช้งานแบรนด์จริง', 'violet', ARRAY['Midjourney','Claude'], 2, true, true, 13)
on conflict (slug) do update set title=excluded.title, tag=excluded.tag, description=excluded.description, tone=excluded.tone, tools=excluded.tools, weeks=excluded.weeks, is_pro=excluded.is_pro, is_published=true, order_index=excluded.order_index;

insert into path_modules (path_id, title, order_index)
select cp.id, v.title, v.ord from career_paths cp, (values
  ('พื้นฐานสร้างภาพด้วย Midjourney', 1),
  ('คุมสไตล์และใช้งานจริง', 2),
  ('งานออกแบบและภาพประกอบกับ Claude', 3)
) as v(title, ord) where cp.slug = 'ai-for-image';

insert into path_steps (module_id, title, kind, course_slug, lesson_num, xp, order_index)
select m.id, v.title, v.kind, v.course_slug, v.lesson_num, v.xp, v.ord
from path_modules m join career_paths cp on cp.id = m.path_id, (values
  (1, 'Midjourney คืออะไร', 'lesson', 'midjourney-basic', 1, 10, 1),
  (1, 'คำสั่ง /imagine แรก', 'lesson', 'midjourney-basic', 2, 10, 2),
  (1, 'โครงสร้าง Prompt ที่ดี', 'lesson', 'midjourney-basic', 3, 10, 3),
  (1, 'พารามิเตอร์: --ar --v --style', 'lesson', 'midjourney-basic', 4, 10, 4),
  (1, 'Image Prompt และภาพอ้างอิง', 'quiz', 'midjourney-basic', 5, 15, 5),
  (2, 'Vary, Upscale และ Remix', 'lesson', 'midjourney-basic', 6, 10, 1),
  (2, 'คุมสไตล์ให้สม่ำเสมอ (--sref --cref)', 'lesson', 'midjourney-basic', 7, 10, 2),
  (2, 'นำภาพไปใช้จริงและลิขสิทธิ์', 'checkpoint', 'midjourney-basic', 8, 30, 3),
  (3, 'AI ในกระบวนการออกแบบ', 'lesson', 'claude-design', 1, 10, 1),
  (3, 'Design Brief & Creative Brief', 'lesson', 'claude-design', 2, 10, 2),
  (3, 'Mood Board และ Reference', 'quiz', 'claude-design', 3, 15, 3),
  (3, 'UX Copy คืออะไร', 'lesson', 'claude-design', 4, 10, 4),
  (3, 'Error Messages และ Microcopy', 'lesson', 'claude-design', 5, 10, 5),
  (3, 'Onboarding Copy', 'checkpoint', 'claude-design', 6, 20, 6)
) as v(mord, title, kind, course_slug, lesson_num, xp, ord)
where cp.slug = 'ai-for-image' and m.order_index = v.mord;



