// Reads the bundled docs.json (generated by scripts/gen-docs.mjs) and exposes the
// same groupings the web /docs hub uses.
export type DocLevel = 'beginner' | 'intermediate' | 'pro';

export type Doc = {
  slug: string;
  title: string;
  tool: string;
  toolSlug: string;
  icon: string;
  level: DocLevel;
  summary: string;
  readTime: string;
  locked: boolean;
  order: number;
  body: string;
};

export type ToolGroup = {
  tool: string;
  toolSlug: string;
  count: number;
  levels: DocLevel[];
  summary: string;
  anyLocked: boolean;
};

export const LEVELS: Record<DocLevel, { label: string; tag: string; free: boolean }> = {
  beginner: { label: 'Beginner', tag: 'ฟรี', free: true },
  intermediate: { label: 'Intermediate', tag: 'Pro', free: false },
  pro: { label: 'Pro', tag: 'Pro', free: false },
};

const LEVEL_ORDER: Record<DocLevel, number> = { beginner: 0, intermediate: 1, pro: 2 };

const ALL: Doc[] = require('../content/docs.json') as Doc[];

export function getToolGroups(): ToolGroup[] {
  const map = new Map<string, ToolGroup>();
  for (const d of ALL) {
    const g = map.get(d.toolSlug);
    if (g) {
      g.count++;
      if (!g.levels.includes(d.level)) g.levels.push(d.level);
      if (d.locked) g.anyLocked = true;
      if (!g.summary) g.summary = d.summary;
    } else {
      map.set(d.toolSlug, {
        tool: d.tool,
        toolSlug: d.toolSlug,
        count: 1,
        levels: [d.level],
        summary: d.summary,
        anyLocked: d.locked,
      });
    }
  }
  for (const g of map.values()) g.levels.sort((a, b) => LEVEL_ORDER[a] - LEVEL_ORDER[b]);
  return [...map.values()].sort((a, b) => a.tool.localeCompare(b.tool));
}

export function getDocsForTool(toolSlug: string): { tool: string; docs: Doc[] } {
  const docs = ALL.filter((d) => d.toolSlug === toolSlug).sort(
    (a, b) => LEVEL_ORDER[a.level] - LEVEL_ORDER[b.level] || a.order - b.order,
  );
  return { tool: docs[0]?.tool ?? toolSlug, docs };
}

/** A doc body is gated unless it's the free Beginner level (mirrors web pricing). */
export function isDocLocked(doc: Doc, isPro: boolean): boolean {
  if (isPro) return false;
  return doc.level !== 'beginner' || doc.locked;
}
