// AUTO-GENERATED by scripts/gen-tool-logos.mjs — do not edit by hand.
// Real AI brand logos (from @lobehub/icons-static-png), keyed by tool display name.
const LOGOS: Record<string, number> = {
  "ChatGPT": require('../assets/tool-logos/openai.png'),
  "Claude": require('../assets/tool-logos/claude.png'),
  "Codex": require('../assets/tool-logos/codex.png'),
  "Gemini": require('../assets/tool-logos/gemini.png'),
  "Grok": require('../assets/tool-logos/grok.png'),
  "Kling AI": require('../assets/tool-logos/kling.png'),
  "Midjourney": require('../assets/tool-logos/midjourney.png'),
  "Suno": require('../assets/tool-logos/suno.png'),
  "ElevenLabs": require('../assets/tool-logos/elevenlabs.png'),
  "Runway": require('../assets/tool-logos/runway.png'),
  "Perplexity": require('../assets/tool-logos/perplexity.png'),
  "DALL·E": require('../assets/tool-logos/dalle.png'),
  "Kimi": require('../assets/tool-logos/kimi.png'),
  "Cursor": require('../assets/tool-logos/cursor.png'),
  "Windsurf": require('../assets/tool-logos/windsurf.png'),
  "Ollama": require('../assets/tool-logos/ollama.png'),
  "Hugging Face": require('../assets/tool-logos/huggingface.png'),
  "OpenRouter": require('../assets/tool-logos/openrouter.png'),
  "Google AI Studio": require('../assets/tool-logos/aistudio.png'),
  "Antigravity": require('../assets/tool-logos/antigravity.png'),
  "Lovable": require('../assets/tool-logos/lovable.png'),
  "Replit": require('../assets/tool-logos/replit.png'),
  "Z.ai": require('../assets/tool-logos/zhipu.png'),
  "Prompt": require('../assets/tool-logos/openai.png'),
  "AI Work": require('../assets/tool-logos/openai.png'),
};

export function toolLogo(name: string | undefined | null): number | null {
  if (!name) return null;
  return LOGOS[name] ?? null;
}
