// Copies Thai lesson JSON from the web app into the mobile bundle and generates
// a static require-map (Metro can only resolve static require paths, so we emit
// one entry per lesson file). Bundles BOTH daily-course lessons and the
// career-path (v3) lessons. Re-run whenever lesson content changes:
//   node scripts/gen-content.mjs
import { readdirSync, statSync, mkdirSync, copyFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const here = dirname(fileURLToPath(import.meta.url));
const mobileRoot = join(here, '..');
const webContent = join(mobileRoot, '..', 'web', 'content');

const slugRe = /^[a-z0-9-]+$/;
const fileRe = /^(\d{2})\.json$/;

// Walk one content root (lessons or career-paths) and copy its Thai JSON.
function collect(srcRoot, outRoot) {
  const entries = [];
  if (!existsSync(srcRoot)) return entries;
  for (const slug of readdirSync(srcRoot)) {
    const dir = join(srcRoot, slug);
    if (!slugRe.test(slug) || !statSync(dir).isDirectory()) continue;
    mkdirSync(join(outRoot, slug), { recursive: true });
    for (const file of readdirSync(dir)) {
      const m = file.match(fileRe);
      if (!m) continue; // skip en/ subfolders and non-lesson files
      copyFileSync(join(dir, file), join(outRoot, slug, file));
      entries.push({ slug, num: parseInt(m[1], 10), file });
    }
  }
  entries.sort((a, b) => a.slug.localeCompare(b.slug) || a.num - b.num);
  return entries;
}

const lessons = collect(join(webContent, 'lessons'), join(mobileRoot, 'content', 'lessons'));
const career = collect(join(webContent, 'career-paths'), join(mobileRoot, 'content', 'career-paths'));

const mapEntries = (entries, dir) =>
  entries
    .map((e) => `  '${e.slug}/${e.num}': () => require('../content/${dir}/${e.slug}/${e.file}') as LessonStep[],`)
    .join('\n');

const out = `// AUTO-GENERATED by scripts/gen-content.mjs — do not edit by hand.
import type { LessonStep } from './lesson-types';

// Daily-course lessons, keyed \`\${courseSlug}/\${lessonNum}\`. ${lessons.length} lessons.
const LESSONS: Record<string, () => LessonStep[]> = {
${mapEntries(lessons, 'lessons')}
};

// Career-path (v3) lessons, keyed \`\${pathSlug}/\${stepNum}\`. ${career.length} lessons.
const CAREER_LESSONS: Record<string, () => LessonStep[]> = {
${mapEntries(career, 'career-paths')}
};

export function loadBundledLesson(slug: string, num: number): LessonStep[] | null {
  const loader = LESSONS[\`\${slug}/\${num}\`];
  return loader ? loader() : null;
}

/** Career-path step content (content/career-paths/{pathSlug}/{stepNum}.json),
 *  falling back to the underlying daily course file for older paths. */
export function loadCareerLesson(pathSlug: string, stepNum: number, fallbackSlug?: string, fallbackNum?: number): LessonStep[] | null {
  const loader = CAREER_LESSONS[\`\${pathSlug}/\${stepNum}\`];
  if (loader) return loader();
  if (fallbackSlug && fallbackNum) return loadBundledLesson(fallbackSlug, fallbackNum);
  return null;
}

export function bundledLessonCount(slug: string): number {
  return Object.keys(LESSONS).filter((k) => k.startsWith(\`\${slug}/\`)).length;
}

export function hasBundledCourse(slug: string): boolean {
  return Object.keys(LESSONS).some((k) => k.startsWith(\`\${slug}/\`));
}
`;

writeFileSync(join(mobileRoot, 'lib', 'lesson-content.ts'), out);
console.log(
  `Bundled ${lessons.length} daily lessons + ${career.length} career-path lessons → lib/lesson-content.ts`,
);
